<template>
  <ion-button  expand="block" fill="solid"   @click="home" router-direction="back">  Volver a home</ion-button>

    <ion-content color="light">
      <ion-list :inset="true">
        <ion-item :button="true" :detail="false" id="select-medicamento">
          <ion-label>Seleccion de medicamentos</ion-label>
          <div slot="end" id="selected-medicamento">{{ selectedMedicamentoText }}</div>
          
        </ion-item>
        <ion-title>Medicamentos seleccionados:</ion-title><br>
        <p><label>{{selectedmedicamentos}}</label></p>
       

      </ion-list>
      <ion-img
      src="../src/25.gif"
      alt="The Wisconsin State Capitol building in Madison, WI at night"
    ></ion-img>
    </ion-content>
  
    <ion-modal trigger="select-medicamento" ref="modal">
      <app-typeahead
        class="ion-page"
        title="Medicamentos"
        :items="medicamentos"
        :selectedItems="selectedmedicamentos"
        @selection-change="medicamentoselectionChanged($event)"
        @selection-cancel="modal.$el.dismiss()"
      ></app-typeahead>
    </ion-modal>

    
  </template>
  
  <script lang="ts">
    import { IonContent, IonItem, IonLabel, IonList, IonModal } from '@ionic/vue';
    import { defineComponent, ref } from 'vue';
    import type { Item } from '../types';
    import AppTypeahead from './AppTypeahead.vue';
  
    export default defineComponent({
      components: { AppTypeahead, IonContent, IonItem, IonLabel, IonList, IonModal },
      setup() {
        const medicamentos: Item[] = [
          
          { text: 'SINTROM',value:'SINTROM' },
  { text: 'ACENOCOUMAROL ROSPAW',value:'ACENOCOUMAROL ROSPAW' },
  { text: 'AZECAR',value:'AZECAR' },
  { text: 'QURA MUK',value:'QURA MUK' },
  { text: 'TEMPOTANE',value:'TEMPOTANE' },
  { text: 'ACETILCISTEINA TEVA',value:'ACETILCISTEINA TEVA' },
  { text: 'DENVERMUC 600',value:'DENVERMUC 600' },
  { text: 'BRONCOLIUM',value:'BRONCOLIUM' },
  { text: 'DOSOMUK',value:'DOSOMUK' },
  { text: 'BALIMUC',value:'BALIMUC' },
  { text: 'CISTEFORT',value:'CISTEFORT' },
  { text: 'ACEMUK',value:'ACEMUK' },
  { text: 'BRONCOLIUM 200',value:'BRONCOLIUM 200' },
  { text: 'TOFLUX JARABE',value:'TOFLUX JARABE' },
  { text: 'TOFLUX',value:'TOFLUX' },
  { text: 'ACC EXPECTORANTE',value:'ACC EXPECTORANTE' },
  { text: 'ACEMUK JARABE',value:'ACEMUK JARABE' },
  { text: 'ASPIRINA PREVENT 325',value:'ASPIRINA PREVENT 325' },
  { text: 'ASPIRINA PREVENT',value:'ASPIRINA PREVENT' },
  { text: 'XICLOVIR',value:'XICLOVIR' },
  { text: 'LISOVYR 400',value:'LISOVYR 400' },
  { text: 'LAFEVIR',value:'LAFEVIR' },
  { text: 'LISOVYR CREMA',value:'LISOVYR CREMA' },
  { text: 'LISOVYR SUSPENSION 8%',value:'LISOVYR SUSPENSION 8%' },
  { text: 'POVIRAL',value:'POVIRAL' },
  { text: 'ACERPES',value:'ACERPES' },
  { text: 'XICLOVIR 800',value:'XICLOVIR 800' },
  { text: 'LISOVYR',value:'LISOVYR' },
  { text: 'ZOVIRAX',value:'ZOVIRAX' },
  { text: 'LISOVYR 800',value:'LISOVYR 800' },
  { text: 'NEOTIGASON',value:'NEOTIGASON' },
  { text: 'ALENDRONATO',value:'ALENDRONATO' },
  { text: 'FINDECLIN',value:'FINDECLIN' },
  { text: 'ACTIMAX',value:'ACTIMAX' },
  { text: 'OSTEOFENE',value:'OSTEOFENE' },
  { text: 'ALENATO',value:'ALENATO' },
  { text: 'SILIDRAL 70',value:'SILIDRAL 70' },
  { text: 'BREK',value:'BREK' },
  { text: 'ARENDAL',value:'ARENDAL' },
  { text: 'MARVIL',value:'MARVIL' },
  { text: 'REGENESIS',value:'REGENESIS' },
  { text: 'ALOPURINOL HLB',value:'ALOPURINOL HLB' },
  { text: 'ALLOPURINOL 100 CRAVERI',value:'ALLOPURINOL 100 CRAVERI' },
  { text: 'ALLOPURINOL 300 CRAVERI',value:'ALLOPURINOL 300 CRAVERI' },
  { text: 'ALLOPURINOL HOUDE',value:'ALLOPURINOL HOUDE' },
  { text: 'COLPURIL A RETARD',value:'COLPURIL A RETARD' },
  { text: 'ALLOPURINOL CRAVERI RETA',value:'ALLOPURINOL CRAVERI RETA' },
  { text: 'ALLOPURINOL GADOR',value:'ALLOPURINOL GADOR' },
  { text: 'ALLOPURINOL HEXAL 300',value:'ALLOPURINOL HEXAL 300' },
  { text: 'ALFADIMAN',value:'ALFADIMAN' },
  { text: 'ARTREX RETARD',value:'ARTREX RETARD' },
  { text: 'COLPURIL 300 RETARD',value:'COLPURIL 300 RETARD' },
  { text: 'COLPURIL',value:'COLPURIL' },
  { text: 'CALLPAX',value:'CALLPAX' },
  { text: 'PRINOX 0.25 MG',value:'PRINOX 0.25 MG' },
  { text: 'PRINOX 2 MG',value:'PRINOX 2 MG' },
  { text: 'PRINOX 0.5 MG',value:'PRINOX 0.5 MG' },
  { text: 'PRINOX 1 MG',value:'PRINOX 1 MG' },
  { text: 'TRANQUINAL',value:'TRANQUINAL' },
  { text: 'ROSPAZ',value:'ROSPAZ' },
  { text: 'ALPRAZOLAM DENVER FARMA',value:'ALPRAZOLAM DENVER FARMA' },
  { text: 'EMERAL',value:'EMERAL' },
  { text: 'ALPRAZOL',value:'ALPRAZOL' },
  { text: 'TENSIUM SL',value:'TENSIUM SL' },
  { text: 'PTA',value:'PTA' },
  { text: 'ALPLAX XR',value:'ALPLAX XR' },
  { text: 'TENSIUM',value:'TENSIUM' },
  { text: 'ALPLAX',value:'ALPLAX' },
  { text: 'XANAX',value:'XANAX' },
  { text: 'MYLANTA II FRUTAL',value:'MYLANTA II FRUTAL' },
  { text: 'MYLANTA II',value:'MYLANTA II' },
  { text: 'ACI-TIP',value:'ACI-TIP' },
  { text: 'FACTOR AG ANTIACIDO',value:'FACTOR AG ANTIACIDO' },
  { text: 'MEGATRIC',value:'MEGATRIC' },
  { text: 'MYLANTA SIMPLE',value:'MYLANTA SIMPLE' },
  { text: 'AMPAKINE',value:'AMPAKINE' },
  { text: 'VIROSOL',value:'VIROSOL' },
  { text: 'ACTISON',value:'ACTISON' },
  { text: 'AMIODARONA HLB',value:'AMIODARONA HLB' },
  { text: 'RITMONIL 200',value:'RITMONIL 200' },
  { text: 'ATLANSIL',value:'ATLANSIL' },
  { text: 'AMIPTRIL',value:'AMIPTRIL' },
  { text: 'TRYPTALGIN',value:'TRYPTALGIN' },
  { text: 'TRYPTANOL',value:'TRYPTANOL' },
  { text: 'AMLODIPINA HLB',value:'AMLODIPINA HLB' },
  { text: 'INDALTEN',value:'INDALTEN' },
  { text: 'AMLOC ODT',value:'AMLOC ODT' },
  { text: 'AMZE',value:'AMZE' },
  { text: 'AMLOPAW',value:'AMLOPAW' },
  { text: 'TENSIMED',value:'TENSIMED' },
  { text: 'AMLODIPINA DENVER FARMA',value:'AMLODIPINA DENVER FARMA' },
  { text: 'HIPERTENSAL',value:'HIPERTENSAL' },
  { text: 'CARDIVAS',value:'CARDIVAS' },
  { text: 'CALPRES',value:'CALPRES' },
  { text: 'ILDUC',value:'ILDUC' },
  { text: 'ZUNDIC',value:'ZUNDIC' },
  { text: 'AMLODINE',value:'AMLODINE' },
  { text: 'TERVALON',value:'TERVALON' },
  { text: 'ARTERIOSAN',value:'ARTERIOSAN' },
  { text: 'CARDIOREX',value:'CARDIOREX' },
  { text: 'TERLOC',value:'TERLOC' },
  { text: 'PELMEC',value:'PELMEC' },
  { text: 'COROVAL',value:'COROVAL' },
  { text: 'AMLOC',value:'AMLOC' },
  { text: 'PELMEC PLUS',value:'PELMEC PLUS' },
  { text: 'TEMAX',value:'TEMAX' },
  { text: 'ILDUC DUO',value:'ILDUC DUO' },
  { text: 'ARTERIOSAN PLUS',value:'ARTERIOSAN PLUS' },
  { text: 'PELMEC DUO',value:'PELMEC DUO' },
  { text: 'TERLOC DUO',value:'TERLOC DUO' },
  { text: 'PRISONIL A',value:'PRISONIL A' },
  { text: 'PRESIMAX A',value:'PRESIMAX A' },
  { text: 'ILDUSARTAN',value:'ILDUSARTAN' },
  { text: 'ARTERIOSAN COMPUESTO',value:'ARTERIOSAN COMPUESTO' },
  { text: 'CARTAN MAX 5/100',value:'CARTAN MAX 5/100' },
  { text: 'CARTAN MAX 5/50',value:'CARTAN MAX 5/50' },
  { text: 'LOSACOR A',value:'LOSACOR A' },
  { text: 'NITEN MAX 5/100',value:'NITEN MAX 5/100' },
  { text: 'NITEN MAX 5/50',value:'NITEN MAX 5/50' },
  { text: 'PELMEC AT',value:'PELMEC AT' },
  { text: 'FENSARTAN UNIMAX',value:'FENSARTAN UNIMAX' },
  { text: 'PELMEC MAX',value:'PELMEC MAX' },
  { text: 'TERLOC MAX',value:'TERLOC MAX' },
  { text: 'PELMEC MAX D',value:'PELMEC MAX D' },
  { text: 'AMOXIFARMA',value:'AMOXIFARMA' },
  { text: 'AMOXOL 500',value:'AMOXOL 500' },
  { text: 'ELGYMOX DUO',value:'ELGYMOX DUO' },
  { text: 'ELGYMOX',value:'ELGYMOX' },
  { text: 'GRINSIL DUO',value:'GRINSIL DUO' },
  { text: 'AMOXOL DUO',value:'AMOXOL DUO' },
  { text: 'AMOXIDAL DUO',value:'AMOXIDAL DUO' },
  { text: 'AMIXEN DUO',value:'AMIXEN DUO' },
  { text: 'TELMOX',value:'TELMOX' },
  { text: 'GRINSIL',value:'GRINSIL' },
  { text: 'AMIXEN',value:'AMIXEN' },
  { text: 'AMOXIDAL',value:'AMOXIDAL' },
  { text: 'AMOXOL 1000',value:'AMOXOL 1000' },
  { text: 'TRIFAMOX DUO',value:'TRIFAMOX DUO' },
  { text: 'TRIFAMOX',value:'TRIFAMOX' },
  { text: 'CISTEFORT DUO',value:'CISTEFORT DUO' },
  { text: 'AMOXIFARMA DUO',value:'AMOXIFARMA DUO' },
  { text: 'CLAMOXOL DUO',value:'CLAMOXOL DUO' },
  { text: 'ELGYMOX CLAV',value:'ELGYMOX CLAV' },
  { text: 'AMOCLAV SE',value:'AMOCLAV SE' },
  { text: 'CLAVULOX ES',value:'CLAVULOX ES' },
  { text: 'CLAVULOX XR',value:'CLAVULOX XR' },
  { text: 'OPTAMOX DUO 14:1',value:'OPTAMOX DUO 14:1' },
  { text: 'GRINSIL CLAV DUO',value:'GRINSIL CLAV DUO' },
  { text: 'AMOCLAV DUO',value:'AMOCLAV DUO' },
  { text: 'OPTAMOX DUO',value:'OPTAMOX DUO' },
  { text: 'ULTRABIOTIC DUO',value:'ULTRABIOTIC DUO' },
  { text: 'BIOCLAVID 400/57',value:'BIOCLAVID 400/57' },
  { text: 'BIOCLAVID 875/125',value:'BIOCLAVID 875/125' },
  { text: 'AMOCLAV',value:'AMOCLAV' },
  { text: 'GRINSIL CLAV DUO 875',value:'GRINSIL CLAV DUO 875' },
  { text: 'BIOCLAVID 500/125',value:'BIOCLAVID 500/125' },
  { text: 'AMIXEN CLAVULANICO 1 G',value:'AMIXEN CLAVULANICO 1 G' },
  { text: 'AMIXEN CLAVULANICO',value:'AMIXEN CLAVULANICO' },
  { text: 'CLAVULOX',value:'CLAVULOX' },
  { text: 'CLAVULOX DUO',value:'CLAVULOX DUO' },
  { text: 'GRINSIL CLAV',value:'GRINSIL CLAV' },
  { text: 'OPTAMOX',value:'OPTAMOX' },
  { text: 'TRIFAMOX IBL DUO',value:'TRIFAMOX IBL DUO' },
  { text: 'TRIFAMOX IBL',value:'TRIFAMOX IBL' },
  { text: 'AMPICILINA HLB',value:'AMPICILINA HLB' },
  { text: 'TRIFACILINA',value:'TRIFACILINA' },
  { text: 'TRIFACILINA IBL',value:'TRIFACILINA IBL' },
  { text: 'TETAVAX',value:'TETAVAX' },
  { text: 'AVAXIM 80 U PEDIATRICO',value:'AVAXIM 80 U PEDIATRICO' },
  { text: 'VAQTA 50',value:'VAQTA 50' },
  { text: 'VAQTA 25',value:'VAQTA 25' },
  { text: 'AVAXIM',value:'AVAXIM' },
  { text: 'HAVRIX 1440 EL.U. ADULTOS',value:'HAVRIX 1440 EL.U. ADULTOS' },
  { text: 'HAVRIX 720 EL.U. MONO DOSI',value:'HAVRIX 720 EL.U. MONO DOSI' },
  { text: 'HEPATIVAX JUNIOR',value:'HEPATIVAX JUNIOR' },
  { text: 'HEPATIVAX',value:'HEPATIVAX' },
  { text: 'BIOVAC HB',value:'BIOVAC HB' },
  { text: 'ENGERIX-B',value:'ENGERIX-B' },
  { text: 'PIXABAN',value:'PIXABAN' },
  { text: 'IXIPEN',value:'IXIPEN' },
  { text: 'APITENA',value:'APITENA' },
  { text: 'PRAXANT',value:'PRAXANT' },
  { text: 'ELIQUIS',value:'ELIQUIS' },
  { text: 'VERICORDIN',value:'VERICORDIN' },
  { text: 'LOLATENO',value:'LOLATENO' },
  { text: 'PLENACOR',value:'PLENACOR' },
  { text: 'ATENOLOL GADOR',value:'ATENOLOL GADOR' },
  { text: 'ATEL',value:'ATEL' },
  { text: 'NORMOLIPOL',value:'NORMOLIPOL' },
  { text: 'LIPOSTOP',value:'LIPOSTOP' },
  { text: 'VASTINA',value:'VASTINA' },
  { text: 'ATEROCLAR',value:'ATEROCLAR' },
  { text: 'TORIVAS',value:'TORIVAS' },
  { text: 'AMPLIAR',value:'AMPLIAR' },
  { text: 'ATORVASTATINA HLB',value:'ATORVASTATINA HLB' },
  { text: 'LIPITOR',value:'LIPITOR' },
  { text: 'LIPONORM',value:'LIPONORM' },
  { text: 'LIPEND',value:'LIPEND' },
  { text: 'LIPIFEN',value:'LIPIFEN' },
  { text: 'LIPOCAMBI',value:'LIPOCAMBI' },
  { text: 'LIPAREX',value:'LIPAREX' },
  { text: 'NORMALIP',value:'NORMALIP' },
  { text: 'PLAN',value:'PLAN' },
  { text: 'LIPIBEC',value:'LIPIBEC' },
  { text: 'ZARATOR',value:'ZARATOR' },
  { text: 'ATEROCLAR DUO',value:'ATEROCLAR DUO' },
  { text: 'COLMIBE',value:'COLMIBE' },
  { text: 'ZARATOR PLUS',value:'ZARATOR PLUS' },
  { text: 'LIPONORM PLUS',value:'LIPONORM PLUS' },
  { text: 'LIPIBEC PLUS',value:'LIPIBEC PLUS' },
  { text: 'LIPOCAMBI PLUS',value:'LIPOCAMBI PLUS' },
  { text: 'AMPLIAR PLUS',value:'AMPLIAR PLUS' },
  { text: 'ATEROCLAR COMBI',value:'ATEROCLAR COMBI' },
  { text: 'LIPAREX PLUS 20',value:'LIPAREX PLUS 20' },
  { text: 'LIPAREX PLUS 10',value:'LIPAREX PLUS 10' },
  { text: 'PLAN DUO',value:'PLAN DUO' },
  { text: 'TORIMIBE',value:'TORIMIBE' },
  { text: 'LIPAREX DUO',value:'LIPAREX DUO' },
  { text: 'AMPLIAR DUO',value:'AMPLIAR DUO' },
  { text: 'HIPOSTEROL',value:'HIPOSTEROL' },
  { text: 'AZATIOPRINA RONTAG',value:'AZATIOPRINA RONTAG' },
  { text: 'AZATIOPRINA RAFFO',value:'AZATIOPRINA RAFFO' },
  { text: 'TREXBIOTIC',value:'TREXBIOTIC' },
  { text: 'MICINAZITRO',value:'MICINAZITRO' },
  { text: 'TRIAMID',value:'TRIAMID' },
  { text: 'TROMIATLAS',value:'TROMIATLAS' },
  { text: 'MACROMAX PEDIATRICO',value:'MACROMAX PEDIATRICO' },
  { text: 'VISAG',value:'VISAG' },
  { text: 'CETAXIM',value:'CETAXIM' },
  { text: 'AZIBIOTIC 500',value:'AZIBIOTIC 500' },
  { text: 'MISULTINA',value:'MISULTINA' },
  { text: 'CRONOPEN',value:'CRONOPEN' },
  { text: 'DOYLE',value:'DOYLE' },
  { text: 'TRITAB',value:'TRITAB' },
  { text: 'MACROMAX',value:'MACROMAX' },
  { text: 'OROBIOTIC',value:'OROBIOTIC' },
  { text: 'NEBLIC',value:'NEBLIC' },
  { text: 'ZITROMAX',value:'ZITROMAX' },
  { text: 'MACROMAX 2G',value:'MACROMAX 2G' },
  { text: 'BALTIC',value:'BALTIC' },
  { text: 'BACLOX',value:'BACLOX' },
  { text: 'FLIMAB',value:'FLIMAB' },
  { text: 'LIORESAL',value:'LIORESAL' },
  { text: 'ACNESAN',value:'ACNESAN' },
  { text: 'VIXIDERM E',value:'VIXIDERM E' },
  { text: 'PERCLIN',value:'PERCLIN' },
  { text: 'RILIF',value:'RILIF' },
  { text: 'RONISTINA DUO MD',value:'RONISTINA DUO MD' },
  { text: 'BETINA',value:'BETINA' },
  { text: 'OTEVIL',value:'OTEVIL' },
  { text: 'AUDIPAX 16',value:'AUDIPAX 16' },
  { text: 'AUDIPAX MULTIDOSIS',value:'AUDIPAX MULTIDOSIS' },
  { text: 'BETASERC',value:'BETASERC' },
  { text: 'RONISTINA',value:'RONISTINA' },
  { text: 'MENIEX',value:'MENIEX' },
  { text: 'RONISTINA DUO',value:'RONISTINA DUO' },
  { text: 'BETACORT CASSARA',value:'BETACORT CASSARA' },
  { text: 'LAZAR CORT',value:'LAZAR CORT' },
  { text: 'CORTICAS',value:'CORTICAS' },
  { text: 'NOVOCORT',value:'NOVOCORT' },
  { text: 'DEPOCORT',value:'DEPOCORT' },
  { text: 'DICASONE 0.6',value:'DICASONE 0.6' },
  { text: 'CORTEROID',value:'CORTEROID' },
  { text: 'BLACOR',value:'BLACOR' },
  { text: 'CELESTONE',value:'CELESTONE' },
  { text: 'BETNOVATE',value:'BETNOVATE' },
  { text: 'BETNOVATE CAPILAR',value:'BETNOVATE CAPILAR' },
  { text: 'DIPROSONE',value:'DIPROSONE' },
  { text: 'CELESTONE CRONODOSE',value:'CELESTONE CRONODOSE' },
  { text: 'DELTISONA RETARD',value:'DELTISONA RETARD' },
  { text: 'DEPOCORT RETARD',value:'DEPOCORT RETARD' },
  { text: 'CORTICAS RETARD',value:'CORTICAS RETARD' },
  { text: 'CRONODICASONE',value:'CRONODICASONE' },
  { text: 'CORTEROID RETARD',value:'CORTEROID RETARD' },
  { text: 'DEPOCORT CRONO',value:'DEPOCORT CRONO' },
  { text: 'CRONODICASONE DEPOT',value:'CRONODICASONE DEPOT' },
  { text: 'CRONO CORTICAS',value:'CRONO CORTICAS' },
  { text: 'CRONOCORTEROID',value:'CRONOCORTEROID' },
  { text: 'DICASONE',value:'DICASONE' },
  { text: 'DERMA 3',value:'DERMA 3' },
  { text: 'LAZAR CORT COMPLEX',value:'LAZAR CORT COMPLEX' },
  { text: 'DEPOCORT BIOTIC',value:'DEPOCORT BIOTIC' },
  { text: 'CUTA',value:'CUTA' },
  { text: 'FACTOR DERMICO',value:'FACTOR DERMICO' },
  { text: 'DENVERCREM DENVER FARM',value:'DENVERCREM DENVER FARM' },
  { text: 'HIFAMONIL CREMA',value:'HIFAMONIL CREMA' },
  { text: 'TRIPLEX',value:'TRIPLEX' },
  { text: 'MACRIL',value:'MACRIL' },
  { text: 'DEXALERGIN NF',value:'DEXALERGIN NF' },
  { text: 'BACTICORT',value:'BACTICORT' },
  { text: 'DIPROGENTA',value:'DIPROGENTA' },
  { text: 'BETNOVATE N',value:'BETNOVATE N' },
  { text: 'BEZACUR',value:'BEZACUR' },
  { text: 'ELPI LIP',value:'ELPI LIP' },
  { text: 'BEZALIP RETARD',value:'BEZALIP RETARD' },
  { text: 'LASIN',value:'LASIN' },
  { text: 'LUMIGAN UD',value:'LUMIGAN UD' },
  { text: 'LATISSE TM',value:'LATISSE TM' },
  { text: 'LUMIGAN RC',value:'LUMIGAN RC' },
  { text: 'LUMIGAN',value:'LUMIGAN' },
  { text: 'GANFORT UD',value:'GANFORT UD' },
  { text: 'GANFORT',value:'GANFORT' },
  { text: 'BIPERIDENO HLB',value:'BIPERIDENO HLB' },
  { text: 'BIPERIDENO ROSPAW',value:'BIPERIDENO ROSPAW' },
  { text: 'AKINETON',value:'AKINETON' },
  { text: 'CORBIS',value:'CORBIS' },
  { text: 'CARDIPLEN',value:'CARDIPLEN' },
  { text: 'BICARDIL',value:'BICARDIL' },
  { text: 'BISOPROLOL TEVA',value:'BISOPROLOL TEVA' },
  { text: 'BISOPIL',value:'BISOPIL' },
  { text: 'BIPROSOL 5 MG',value:'BIPROSOL 5 MG' },
  { text: 'BIPROSOL 10 MG',value:'BIPROSOL 10 MG' },
  { text: 'LOSTAPROLOL',value:'LOSTAPROLOL' },
  { text: 'CONCOR',value:'CONCOR' },
  { text: 'CORBIS D',value:'CORBIS D' },
  { text: 'CONCOR PLUS',value:'CONCOR PLUS' },
  { text: 'BRIMOPRESS',value:'BRIMOPRESS' },
  { text: 'ALPHAGAN P',value:'ALPHAGAN P' },
  { text: 'ALPHAGAN',value:'ALPHAGAN' },
  { text: 'BRIT',value:'BRIT' },
  { text: 'BRIMOPRESS T',value:'BRIMOPRESS T' },
  { text: 'TIMOBRIM',value:'TIMOBRIM' },
  { text: 'COMBIGAN',value:'COMBIGAN' },
  { text: 'BROMEXIDRIL',value:'BROMEXIDRIL' },
  { text: 'RINO-B NEBU CON DILUYENTE',value:'RINO-B NEBU CON DILUYENTE' },
  { text: 'NEUMOCORT + AEROMED',value:'NEUMOCORT + AEROMED' },
  { text: 'NEUMOCORT HFA',value:'NEUMOCORT HFA' },
  { text: 'BUDESONIDA DF NEBU',value:'BUDESONIDA DF NEBU' },
  { text: 'BUDESONIDA DF BRONQUIAL',value:'BUDESONIDA DF BRONQUIAL' },
  { text: 'RINO-B 100',value:'RINO-B 100' },
  { text: 'PROETZONIDE NEBU',value:'PROETZONIDE NEBU' },
  { text: 'RINO-B NEBU',value:'RINO-B NEBU' },
  { text: 'HYPERSOL B 100',value:'HYPERSOL B 100' },
  { text: 'HYPERSOL B 50',value:'HYPERSOL B 50' },
  { text: 'RINO-B 50',value:'RINO-B 50' },
  { text: 'BUDENOFALK',value:'BUDENOFALK' },
  { text: 'CORTIMENT',value:'CORTIMENT' },
  { text: 'AEROVIAL HFA',value:'AEROVIAL HFA' },
  { text: 'NEUMOTEX NEBU',value:'NEUMOTEX NEBU' },
  { text: 'NEUMOTEX BRONQUIAL PEDIA',value:'NEUMOTEX BRONQUIAL PEDIA' },
  { text: 'NEUMOTEX BRONQUIAL CON',value:'NEUMOTEX BRONQUIAL CON' },
  { text: 'NEUMOTEX BRONQUIAL',value:'NEUMOTEX BRONQUIAL' },
  { text: 'NEUMOTEX 400',value:'NEUMOTEX 400' },
  { text: 'NEUMOTEX 200',value:'NEUMOTEX 200' },
  { text: 'BUDESON NEBU',value:'BUDESON NEBU' },
  { text: 'ENTOCORT',value:'ENTOCORT' },
  { text: 'NEUMOTEX BRONQUIAL FORT',value:'NEUMOTEX BRONQUIAL FORT' },
  { text: 'SPIROCORT TURBUHALER',value:'SPIROCORT TURBUHALER' },
  { text: 'NEUMOTEX NASAL',value:'NEUMOTEX NASAL' },
  { text: 'NEUMOCORT PLUS',value:'NEUMOCORT PLUS' },
  { text: 'LIERBRON',value:'LIERBRON' },
  { text: 'NEUMOTEROL AEROSOL',value:'NEUMOTEROL AEROSOL' },
  { text: 'FORMOVENT + BUDE',value:'FORMOVENT + BUDE' },
  { text: 'FREVIA',value:'FREVIA' },
  { text: 'NEUMOTEROL 400',value:'NEUMOTEROL 400' },
  { text: 'SYMBICORT-FORTE TURBUHA',value:'SYMBICORT-FORTE TURBUHA' },
  { text: 'SYMBICORT-M TURBUHALER',value:'SYMBICORT-M TURBUHALER' },
  { text: 'NEUMOTEROL 200',value:'NEUMOTEROL 200' },
  { text: 'SYMBICORT TURBUHALER',value:'SYMBICORT TURBUHALER' },
  { text: 'BUFLOMEDIL LAFEDAR',value:'BUFLOMEDIL LAFEDAR' },
  { text: 'CABERTRIX',value:'CABERTRIX' },
  { text: 'LACTAMAX',value:'LACTAMAX' },
  { text: 'DOSTINEX',value:'DOSTINEX' },
  { text: 'CABERPAR',value:'CABERPAR' },
  { text: 'CABASER',value:'CABASER' },
  { text: 'CALCIO BASE DUPOMAR FORT',value:'CALCIO BASE DUPOMAR FORT' },
  { text: 'CALCIONAL',value:'CALCIONAL' },
  { text: 'CALCIO BASE DUPOMAR',value:'CALCIO BASE DUPOMAR' },
  { text: 'CALCIO BASE DUPOMAR D3 40',value:'CALCIO BASE DUPOMAR D3 40' },
  { text: 'CALCIO BASE DUPOMAR D3 20',value:'CALCIO BASE DUPOMAR D3 20' },
  { text: 'CALCIO BASE DUPOMAR D',value:'CALCIO BASE DUPOMAR D' },
  { text: 'TAXUS 400',value:'TAXUS 400' },
  { text: 'CALCIONAL CITRATO',value:'CALCIONAL CITRATO' },
  { text: 'CALCIMAX FORTE',value:'CALCIMAX FORTE' },
  { text: 'CALCIMAX',value:'CALCIMAX' },
  { text: 'CALCIONAL D3 400',value:'CALCIONAL D3 400' },
  { text: 'CALCIMAX D3 400',value:'CALCIMAX D3 400' },
  { text: 'CALCIOCIT PLUS',value:'CALCIOCIT PLUS' },
  { text: 'CITRAMAR D 400',value:'CITRAMAR D 400' },
  { text: 'CITRAMAR D 200',value:'CITRAMAR D 200' },
  { text: 'CALCIONAL D3',value:'CALCIONAL D3' },
  { text: 'CALCIMAX D3',value:'CALCIMAX D3' },
  { text: 'CALCIOCIT',value:'CALCIOCIT' },
  { text: 'CUTANIT LOCION',value:'CUTANIT LOCION' },
  { text: 'CUTANIT',value:'CUTANIT' },
  { text: 'DAIVONEX',value:'DAIVONEX' },
  { text: 'CUTANIT B',value:'CUTANIT B' },
  { text: 'BETRIOL B',value:'BETRIOL B' },
  { text: 'CALCI CORTICAS',value:'CALCI CORTICAS' },
  { text: 'CALCIRAQUIFEROL',value:'CALCIRAQUIFEROL' },
  { text: 'CALCITRIOL RAYMOS',value:'CALCITRIOL RAYMOS' },
  { text: 'CALCITRIOL',value:'CALCITRIOL' },
  { text: 'TEGRETOL',value:'TEGRETOL' },
  { text: 'CARBAMAZEPINA DENVER FA',value:'CARBAMAZEPINA DENVER FA' },
  { text: 'ACTINERVAL',value:'ACTINERVAL' },
  { text: 'CARBAMAT',value:'CARBAMAT' },
  { text: 'ELEBE',value:'ELEBE' },
  { text: 'CONFORMAL',value:'CONFORMAL' },
  { text: 'TEGRETOL 400 LC',value:'TEGRETOL 400 LC' },
  { text: 'OMEGA 100',value:'OMEGA 100' },
  { text: 'OMEGA 100 EXPECTORANTE',value:'OMEGA 100 EXPECTORANTE' },
  { text: 'MUCOLITIC UD',value:'MUCOLITIC UD' },
  { text: 'MUCOLITIC',value:'MUCOLITIC' },
  { text: 'VEDILEP 3.125',value:'VEDILEP 3.125' },
  { text: 'ISOBLOC',value:'ISOBLOC' },
  { text: 'CARVEDIL RETARD',value:'CARVEDIL RETARD' },
  { text: 'CARVEDIL',value:'CARVEDIL' },
  { text: 'ZONCORA',value:'ZONCORA' },
  { text: 'DILATREND',value:'DILATREND' },
  { text: 'CARVIPAW',value:'CARVIPAW' },
  { text: 'VERATEN UD',value:'VERATEN UD' },
  { text: 'VERATEN',value:'VERATEN' },
  { text: 'VEDILEP 25',value:'VEDILEP 25' },
  { text: 'BIDECAR',value:'BIDECAR' },
  { text: 'CARTIATO',value:'CARTIATO' },
  { text: 'VEDILEP 6.25',value:'VEDILEP 6.25' },
  { text: 'VEDILEP 12.5',value:'VEDILEP 12.5' },
  { text: 'FILTEN LP',value:'FILTEN LP' },
  { text: 'VICARDOL',value:'VICARDOL' },
  { text: 'DILATREND AP',value:'DILATREND AP' },
  { text: 'BIDECAR CR',value:'BIDECAR CR' },
  { text: 'CARDIONORM',value:'CARDIONORM' },
  { text: 'FILTEN',value:'FILTEN' },
  { text: 'ANTIBLOC 25',value:'ANTIBLOC 25' },
  { text: 'ANTIBLOC 12.5',value:'ANTIBLOC 12.5' },
  { text: 'ANTIBLOC 6.25',value:'ANTIBLOC 6.25' },
  { text: 'CORAFEN',value:'CORAFEN' },
  { text: 'CORUBIN',value:'CORUBIN' },
  { text: 'DUOBLOC',value:'DUOBLOC' },
  { text: 'ISOBLOC CR 40 MG',value:'ISOBLOC CR 40 MG' },
  { text: 'ISOBLOC CR 20 MG',value:'ISOBLOC CR 20 MG' },
  { text: 'CARVEDIL D',value:'CARVEDIL D' },
  { text: 'BIDECAR D',value:'BIDECAR D' },
  { text: 'FILTEN D',value:'FILTEN D' },
  { text: 'DILATREND D',value:'DILATREND D' },
  { text: 'ISOBLOC D',value:'ISOBLOC D' },
  { text: 'CEFADROX 250',value:'CEFADROX 250' },
  { text: 'CEFACAR',value:'CEFACAR' },
  { text: 'CEFACILINA',value:'CEFACILINA' },
  { text: 'CEFALEXINA HLB',value:'CEFALEXINA HLB' },
  { text: 'SEPTILISIN',value:'SEPTILISIN' },
  { text: 'CEPOREXIN DUO 1 GR',value:'CEPOREXIN DUO 1 GR' },
  { text: 'CEFALEXINA ARGENTIA DUO',value:'CEFALEXINA ARGENTIA DUO' },
  { text: 'CEPOREXIN DUO 750',value:'CEPOREXIN DUO 750' },
  { text: 'SEPTILISIN DUO',value:'SEPTILISIN DUO' },
  { text: 'CEPOREXIN',value:'CEPOREXIN' },
  { text: 'KEFORAL',value:'KEFORAL' },
  { text: 'CEFALEXINA ARGENTIA',value:'CEFALEXINA ARGENTIA' },
  { text: 'CEFOSPOREN',value:'CEFOSPOREN' },
  { text: 'VIXCEF',value:'VIXCEF' },
  { text: 'CEFIXIMA HLB',value:'CEFIXIMA HLB' },
  { text: 'NOVACEF',value:'NOVACEF' },
  { text: 'CEFUROX SABOR MEJORADO',value:'CEFUROX SABOR MEJORADO' },
  { text: 'CEFUROXIMA RICHET SUSPEN',value:'CEFUROXIMA RICHET SUSPEN' },
  { text: 'CELEBREX',value:'CELEBREX' },
  { text: 'CETIRIZINA TEVA',value:'CETIRIZINA TEVA' },
  { text: 'ALIDIAL',value:'ALIDIAL' },
  { text: 'ATOPIX',value:'ATOPIX' },
  { text: 'CETIZINE',value:'CETIZINE' },
  { text: 'CABAL',value:'CABAL' },
  { text: 'STOPALER',value:'STOPALER' },
  { text: 'ZYRTEC',value:'ZYRTEC' },
  { text: 'SALVALERG',value:'SALVALERG' },
  { text: 'CICLOPENTOLATO POEN',value:'CICLOPENTOLATO POEN' },
  { text: 'CITALEXON',value:'CITALEXON' },
  { text: 'VASATIV XR',value:'VASATIV XR' },
  { text: 'CILOSPAW',value:'CILOSPAW' },
  { text: 'ZOLPLAT',value:'ZOLPLAT' },
  { text: 'NOVAMAS',value:'NOVAMAS' },
  { text: 'ACLUSIN',value:'ACLUSIN' },
  { text: 'CILAAL 50',value:'CILAAL 50' },
  { text: 'POLICOR',value:'POLICOR' },
  { text: 'CILOSTAL',value:'CILOSTAL' },
  { text: 'CILOVAS',value:'CILOVAS' },
  { text: 'LICUAGEN',value:'LICUAGEN' },
  { text: 'TRASTOCIR',value:'TRASTOCIR' },
  { text: 'PLETAAL',value:'PLETAAL' },
  { text: 'CILAAL 100',value:'CILAAL 100' },
  { text: 'DENCILOX',value:'DENCILOX' },
  { text: 'PROCTYL',value:'PROCTYL' },
  { text: 'CIRIAX OTIC L',value:'CIRIAX OTIC L' },
  { text: 'CIPROFLOXACINA HLB',value:'CIPROFLOXACINA HLB' },
  { text: 'CIPROMED',value:'CIPROMED' },
  { text: 'SELKET 500',value:'SELKET 500' },
  { text: 'REXNER XR',value:'REXNER XR' },
  { text: 'MEDAFLOX',value:'MEDAFLOX' },
  { text: 'CIPROFLOXACINA DORF',value:'CIPROFLOXACINA DORF' },
  { text: 'CIPROFLOXACINA DENVER FA',value:'CIPROFLOXACINA DENVER FA' },
  { text: 'GINO CIRIAX FORTE',value:'GINO CIRIAX FORTE' },
  { text: 'GINO CIRIAX',value:'GINO CIRIAX' },
  { text: 'REXNER',value:'REXNER' },
  { text: 'FLORAXINA',value:'FLORAXINA' },
  { text: 'EXERTIAL 500',value:'EXERTIAL 500' },
  { text: 'BIOTIC PHARMA',value:'BIOTIC PHARMA' },
  { text: 'CIPROFLOXACINA LAZAR',value:'CIPROFLOXACINA LAZAR' },
  { text: 'ARGEFLOX',value:'ARGEFLOX' },
  { text: 'CIRIAX',value:'CIRIAX' },
  { text: 'SEPTICIDE',value:'SEPTICIDE' },
  { text: 'XIPROMOX',value:'XIPROMOX' },
  { text: 'CIPRO',value:'CIPRO' },
  { text: 'POLEX',value:'POLEX' },
  { text: 'PROCALM',value:'PROCALM' },
  { text: 'FOTAMICIN',value:'FOTAMICIN' },
  { text: 'CIPROFLOXACINA D DORF',value:'CIPROFLOXACINA D DORF' },
  { text: 'OTOSPORIN DEXA',value:'OTOSPORIN DEXA' },
  { text: 'QUIDEX',value:'QUIDEX' },
  { text: 'TACINES',value:'TACINES' },
  { text: 'DECADRON CON CIPROFLOXA',value:'DECADRON CON CIPROFLOXA' },
  { text: 'OTOSPORIN C',value:'OTOSPORIN C' },
  { text: 'OTO BIOTAER',value:'OTO BIOTAER' },
  { text: 'CIPROFLOXACINA LAZAR HC',value:'CIPROFLOXACINA LAZAR HC' },
  { text: 'CIRIAX OTIC',value:'CIRIAX OTIC' },
  { text: 'ZINNIA',value:'ZINNIA' },
  { text: 'AVANCEL',value:'AVANCEL' },
  { text: 'MILEVA 35',value:'MILEVA 35' },
  { text: 'DIANE 35',value:'DIANE 35' },
  { text: 'LENEPAL',value:'LENEPAL' },
  { text: 'CITTA',value:'CITTA' },
  { text: 'HUMORAP',value:'HUMORAP' },
  { text: 'PSICONOR',value:'PSICONOR' },
  { text: 'ZENTIUS',value:'ZENTIUS' },
  { text: 'SEROPRAM',value:'SEROPRAM' },
  { text: 'ISET U.D.',value:'ISET U.D.' },
  { text: 'CLARIDAD',value:'CLARIDAD' },
  { text: 'CLARIMAX UD 1000',value:'CLARIMAX UD 1000' },
  { text: 'CLASID',value:'CLASID' },
  { text: 'CLARICINA',value:'CLARICINA' },
  { text: 'CLAROVIL',value:'CLAROVIL' },
  { text: 'CLARIBIOTIC 250',value:'CLARIBIOTIC 250' },
  { text: 'CLARIBIOTIC 125',value:'CLARIBIOTIC 125' },
  { text: 'QUOTAL UD',value:'QUOTAL UD' },
  { text: 'QUOTAL',value:'QUOTAL' },
  { text: 'CLARIMAX 250',value:'CLARIMAX 250' },
  { text: 'CLARIMAX 125',value:'CLARIMAX 125' },
  { text: 'CLARIMAX UD',value:'CLARIMAX UD' },
  { text: 'CLARIMAX 500',value:'CLARIMAX 500' },
  { text: 'CLAROVIL UD',value:'CLAROVIL UD' },
  { text: 'CLARIBIOTIC U.D.',value:'CLARIBIOTIC U.D.' },
  { text: 'AEROXINA U.D.',value:'AEROXINA U.D.' },
  { text: 'KLARICID',value:'KLARICID' },
  { text: 'AEROXINA',value:'AEROXINA' },
  { text: 'ISET',value:'ISET' },
  { text: 'KLARICID UD',value:'KLARICID UD' },
  { text: 'KLARICID FORTE',value:'KLARICID FORTE' },
  { text: 'CLARITROM',value:'CLARITROM' },
  { text: 'CLARIBIOTIC 500',value:'CLARIBIOTIC 500' },
  { text: 'MICROBION',value:'MICROBION' },
  { text: 'DEXACNE',value:'DEXACNE' },
  { text: 'RESBIOTIC',value:'RESBIOTIC' },
  { text: 'TORGYN',value:'TORGYN' },
  { text: 'CLINDALAF',value:'CLINDALAF' },
  { text: 'DALACIN C 300',value:'DALACIN C 300' },
  { text: 'CLINTOPIC',value:'CLINTOPIC' },
  { text: 'RESBIOTIC PEDIATRICO',value:'RESBIOTIC PEDIATRICO' },
  { text: 'PEROXIDERM',value:'PEROXIDERM' },
  { text: 'PEROXICLIN DUO',value:'PEROXICLIN DUO' },
  { text: 'GINCLIN',value:'GINCLIN' },
  { text: 'OVUMIX MAX',value:'OVUMIX MAX' },
  { text: 'COLPOSAN',value:'COLPOSAN' },
  { text: 'TORGYN DUO',value:'TORGYN DUO' },
  { text: 'KARIDIUM',value:'KARIDIUM' },
  { text: 'PERFRACORT',value:'PERFRACORT' },
  { text: 'SALVICUTAN',value:'SALVICUTAN' },
  { text: 'SALAC',value:'SALAC' },
  { text: 'CLOBEFAR CREMA',value:'CLOBEFAR CREMA' },
  { text: 'CLOBEFAR UNGUENTO',value:'CLOBEFAR UNGUENTO' },
  { text: 'CLOBESOL',value:'CLOBESOL' },
  { text: 'CLOBEPLUS',value:'CLOBEPLUS' },
  { text: 'DERMADEX',value:'DERMADEX' },
  { text: 'DERMADEX CAPILAR',value:'DERMADEX CAPILAR' },
  { text: 'EUMOVATE',value:'EUMOVATE' },
  { text: 'CLOMIFEM',value:'CLOMIFEM' },
  { text: 'TOCOFENO',value:'TOCOFENO' },
  { text: 'CLOMISAL DIVIDOSIS',value:'CLOMISAL DIVIDOSIS' },
  { text: 'ANAFRANIL',value:'ANAFRANIL' },
  { text: 'ANAFRANIL 75 DIVITABS',value:'ANAFRANIL 75 DIVITABS' },
  { text: 'QUAZEMIC SL',value:'QUAZEMIC SL' },
  { text: 'QUAZEMIC',value:'QUAZEMIC' },
  { text: 'EDICTUM 0.5 MG',value:'EDICTUM 0.5 MG' },
  { text: 'EDICTUM 2 MG',value:'EDICTUM 2 MG' },
  { text: 'NAZEPAMCLO',value:'NAZEPAMCLO' },
  { text: 'NEURYL',value:'NEURYL' },
  { text: 'DIOCAM',value:'DIOCAM' },
  { text: 'CLONAX',value:'CLONAX' },
  { text: 'SOLFIDIN FLASH',value:'SOLFIDIN FLASH' },
  { text: 'CLONAZEPAM ROSPAW',value:'CLONAZEPAM ROSPAW' },
  { text: 'CLONAZEPAM DENVER FARM',value:'CLONAZEPAM DENVER FARM' },
  { text: 'DIOCAM SL',value:'DIOCAM SL' },
  { text: 'CLONAGIN 0.5',value:'CLONAGIN 0.5' },
  { text: 'CLONAGIN 2',value:'CLONAGIN 2' },
  { text: 'CLONAGIN SL',value:'CLONAGIN SL' },
  { text: 'INDUZEPAM',value:'INDUZEPAM' },
  { text: 'CLONAX RAPID',value:'CLONAX RAPID' },
  { text: 'RIUCLONAZ',value:'RIUCLONAZ' },
  { text: 'CLONAGIN',value:'CLONAGIN' },
  { text: 'CLONAGIN 0.25',value:'CLONAGIN 0.25' },
  { text: 'CLONAGIN 1',value:'CLONAGIN 1' },
  { text: 'RIVOTRIL',value:'RIVOTRIL' },
  { text: 'SOLFIDIN',value:'SOLFIDIN' },
  { text: 'CLODINAREL',value:'CLODINAREL' },
  { text: 'CLOPILEP',value:'CLOPILEP' },
  { text: 'PLAVIX',value:'PLAVIX' },
  { text: 'CLOPIDOGREL ROSPAW',value:'CLOPIDOGREL ROSPAW' },
  { text: 'PLAQUETRIOL',value:'PLAQUETRIOL' },
  { text: 'CLOPIDOGREL TEVA',value:'CLOPIDOGREL TEVA' },
  { text: 'MONREX',value:'MONREX' },
  { text: 'TROKEN',value:'TROKEN' },
  { text: 'CLODREL',value:'CLODREL' },
  { text: 'NABRATIN',value:'NABRATIN' },
  { text: 'PLEYAR',value:'PLEYAR' },
  { text: 'ANTIPLAQ',value:'ANTIPLAQ' },
  { text: 'NEFAZAN',value:'NEFAZAN' },
  { text: 'NIVAQUINE',value:'NIVAQUINE' },
  { text: 'AMPLIACTIL',value:'AMPLIACTIL' },
  { text: 'EURETICO',value:'EURETICO' },
  { text: 'LOMECAN OVULOS',value:'LOMECAN OVULOS' },
  { text: 'IKOLAN',value:'IKOLAN' },
  { text: 'MICOMAZOL',value:'MICOMAZOL' },
  { text: 'MICOMAZOL DEO',value:'MICOMAZOL DEO' },
  { text: 'CITATON',value:'CITATON' },
  { text: 'CLOZAPINA ROSPAW',value:'CLOZAPINA ROSPAW' },
  { text: 'LAPENAX',value:'LAPENAX' },
  { text: 'DOLOFRIX',value:'DOLOFRIX' },
  { text: 'DOLOFRIX FORTE',value:'DOLOFRIX FORTE' },
  { text: 'G.N.O. CP',value:'G.N.O. CP' },
  { text: 'COLCHICINA HOUDE',value:'COLCHICINA HOUDE' },
  { text: 'NIVELIPOL RESINA',value:'NIVELIPOL RESINA' },
  { text: 'DERCOLINA A',value:'DERCOLINA A' },
  { text: 'DERCOLINA INFANTIL',value:'DERCOLINA INFANTIL' },
  { text: 'DERCOLINA',value:'DERCOLINA' },
  { text: 'DABIDANE',value:'DABIDANE' },
  { text: 'PRADAXA',value:'PRADAXA' },
  { text: 'LADOGAL 200',value:'LADOGAL 200' },
  { text: 'DAPSONA LAZAR',value:'DAPSONA LAZAR' },
  { text: 'DAPSOGEL',value:'DAPSOGEL' },
  { text: 'D.A.P.S.',value:'D.A.P.S.' },
  { text: 'DEFAS',value:'DEFAS' },
  { text: 'AZACORTID',value:'AZACORTID' },
  { text: 'DELORAT',value:'DELORAT' },
  { text: 'DESALER',value:'DESALER' },
  { text: 'NOVO ALERPRIV',value:'NOVO ALERPRIV' },
  { text: 'HEXALER',value:'HEXALER' },
  { text: 'FRENALER',value:'FRENALER' },
  { text: 'AERIUS',value:'AERIUS' },
  { text: 'DELORAT B',value:'DELORAT B' },
  { text: 'PREDUALERGIN CORT',value:'PREDUALERGIN CORT' },
  { text: 'HISTADICASONE',value:'HISTADICASONE' },
  { text: 'DESALER CORT',value:'DESALER CORT' },
  { text: 'HEXALER CORT',value:'HEXALER CORT' },
  { text: 'FRENALER CORT',value:'FRENALER CORT' },
  { text: 'NOCDURNA',value:'NOCDURNA' },
  { text: 'DESMOPRESIN MELT',value:'DESMOPRESIN MELT' },
  { text: 'DINADOM',value:'DINADOM' },
  { text: 'DESMOPRESIN',value:'DESMOPRESIN' },
  { text: 'PINK',value:'PINK' },
  { text: 'CAMELIA',value:'CAMELIA' },
  { text: 'LUMILAC',value:'LUMILAC' },
  { text: 'CARMIN',value:'CARMIN' },
  { text: 'CERAZETTE',value:'CERAZETTE' },
  { text: 'MERCILON',value:'MERCILON' },
  { text: 'MARVELON',value:'MARVELON' },
  { text: 'IXIUM',value:'IXIUM' },
  { text: 'DESLAFAX',value:'DESLAFAX' },
  { text: 'DROSIX',value:'DROSIX' },
  { text: 'VELDEX',value:'VELDEX' },
  { text: 'ALFAXIN',value:'ALFAXIN' },
  { text: 'PRISTIQ',value:'PRISTIQ' },
  { text: 'FAPRIS',value:'FAPRIS' },
  { text: 'DEXALAF',value:'DEXALAF' },
  { text: 'DECADRON',value:'DECADRON' },
  { text: 'DECADRON AL',value:'DECADRON AL' },
  { text: 'DEXATOTAL',value:'DEXATOTAL' },
  { text: 'DEXAMETASONA DORF',value:'DEXAMETASONA DORF' },
  { text: 'DEXAMERAL 4',value:'DEXAMERAL 4' },
  { text: 'SEDESTEROL',value:'SEDESTEROL' },
  { text: 'OZURDEX',value:'OZURDEX' },
  { text: 'DUO DECADRON',value:'DUO DECADRON' },
  { text: 'IDOLGINA',value:'IDOLGINA' },
  { text: 'TACRAF GEL',value:'TACRAF GEL' },
  { text: 'TACRAF',value:'TACRAF' },
  { text: 'ALGICUR',value:'ALGICUR' },
  { text: 'ENANTYUM',value:'ENANTYUM' },
  { text: 'PLIDAN',value:'PLIDAN' },
  { text: 'VALIUM',value:'VALIUM' },
  { text: 'DIAZEPAN MEDIPHARMA',value:'DIAZEPAN MEDIPHARMA' },
  { text: 'SAROMET FULLTIME',value:'SAROMET FULLTIME' },
  { text: 'SAROMET',value:'SAROMET' },
  { text: 'DIACTAL ENEMA',value:'DIACTAL ENEMA' },
  { text: 'DICLOFENAC AP HLB',value:'DICLOFENAC AP HLB' },
  { text: 'DICLOFENAC HLB',value:'DICLOFENAC HLB' },
  { text: 'DIFENAC',value:'DIFENAC' },
  { text: 'DIOXAFLEX CB 75',value:'DIOXAFLEX CB 75' },
  { text: 'DICLOGESIC 100 AP',value:'DICLOGESIC 100 AP' },
  { text: 'KINALGIN',value:'KINALGIN' },
  { text: 'BLOKIUM P',value:'BLOKIUM P' },
  { text: 'DIOXAFLEX MIGRA',value:'DIOXAFLEX MIGRA' },
  { text: 'METAFLEX',value:'METAFLEX' },
  { text: 'VESALION',value:'VESALION' },
  { text: 'OXA 50',value:'OXA 50' },
  { text: 'OXA 75',value:'OXA 75' },
  { text: 'BLOKIUM CORT',value:'BLOKIUM CORT' },
  { text: 'ARIFLENAC FORTE',value:'ARIFLENAC FORTE' },
  { text: 'DICLOFENAC+PARACETAMOL',value:'DICLOFENAC+PARACETAMOL' },
  { text: 'BLOKIUM GESIC FORTE',value:'BLOKIUM GESIC FORTE' },
  { text: 'ARTRO RED',value:'ARTRO RED' },
  { text: 'OXAGESIC FORTE',value:'OXAGESIC FORTE' },
  { text: 'ANAFLEX PLUS RAPIDA ACCIO',value:'ANAFLEX PLUS RAPIDA ACCIO' },
  { text: 'METAFLEX GESIC FORTE',value:'METAFLEX GESIC FORTE' },
  { text: 'DIOXAFLEX CB GESIC',value:'DIOXAFLEX CB GESIC' },
  { text: 'TAFIROL ARTRO',value:'TAFIROL ARTRO' },
  { text: 'METAFLEX GESIC',value:'METAFLEX GESIC' },
  { text: 'DICLOGESIC FORTE',value:'DICLOGESIC FORTE' },
  { text: 'PANCLOGESIC',value:'PANCLOGESIC' },
  { text: 'XEDENOL GESIC',value:'XEDENOL GESIC' },
  { text: 'VESALION GESIC',value:'VESALION GESIC' },
  { text: 'PARACETAMOL FORTE RAFFO',value:'PARACETAMOL FORTE RAFFO' },
  { text: 'BLOKIUM GESIC',value:'BLOKIUM GESIC' },
  { text: 'DIOXAFLEX GESIC',value:'DIOXAFLEX GESIC' },
  { text: 'OXAGESIC',value:'OXAGESIC' },
  { text: 'OXAGESIC CB',value:'OXAGESIC CB' },
  { text: 'DIOXAFLEX',value:'DIOXAFLEX' },
  { text: 'FLEXANA',value:'FLEXANA' },
  { text: 'OXA GEL PLUS',value:'OXA GEL PLUS' },
  { text: 'FLOGOLISIN',value:'FLOGOLISIN' },
  { text: 'XEDENOL CB',value:'XEDENOL CB' },
  { text: 'METAFLEX 75 CB',value:'METAFLEX 75 CB' },
  { text: 'DISIPAN 75 MG',value:'DISIPAN 75 MG' },
  { text: 'METAFLEX 50 CB',value:'METAFLEX 50 CB' },
  { text: 'DIOXAFLEX 5%',value:'DIOXAFLEX 5%' },
  { text: 'DIOXAFLEX CB',value:'DIOXAFLEX CB' },
  { text: 'XEDENOL',value:'XEDENOL' },
  { text: 'METAFLEX 75',value:'METAFLEX 75' },
  { text: 'DICLAC',value:'DICLAC' },
  { text: 'DICLOGESIC',value:'DICLOGESIC' },
  { text: 'BLOKIUM',value:'BLOKIUM' },
  { text: 'METAFLEX 50',value:'METAFLEX 50' },
  { text: 'DICLOFENAC DENVER FARMA',value:'DICLOFENAC DENVER FARMA' },
  { text: 'NATURA FENAC',value:'NATURA FENAC' },
  { text: 'OXA RETARD',value:'OXA RETARD' },
  { text: 'DICLONOVAG',value:'DICLONOVAG' },
  { text: 'DIOXAFLEX RAPID',value:'DIOXAFLEX RAPID' },
  { text: 'BLOKIUM PROTECT',value:'BLOKIUM PROTECT' },
  { text: 'DIOXAFLEX PROTECT',value:'DIOXAFLEX PROTECT' },
  { text: 'DICLOFENAC FLEX HLB',value:'DICLOFENAC FLEX HLB' },
  { text: 'BLOKIUM FLEX',value:'BLOKIUM FLEX' },
  { text: 'XEDENOL FLEX CB',value:'XEDENOL FLEX CB' },
  { text: 'METAFLEX PLUS CB',value:'METAFLEX PLUS CB' },
  { text: 'OXADISTEN CB',value:'OXADISTEN CB' },
  { text: 'DICLOGESIC RELAX',value:'DICLOGESIC RELAX' },
  { text: 'PANCLOFLEX',value:'PANCLOFLEX' },
  { text: 'DIOXAFLEX CB PLUS',value:'DIOXAFLEX CB PLUS' },
  { text: 'VESALION FLEX',value:'VESALION FLEX' },
  { text: 'METAFLEX PLUS',value:'METAFLEX PLUS' },
  { text: 'XEDENOL FLEX',value:'XEDENOL FLEX' },
  { text: 'OXADISTEN',value:'OXADISTEN' },
  { text: 'DIOXAFLEX PLUS',value:'DIOXAFLEX PLUS' },
  { text: 'AZUCENA',value:'AZUCENA' },
  { text: 'RUBI',value:'RUBI' },
  { text: 'QLAIRA',value:'QLAIRA' },
  { text: 'DIFENHIDRAMINA HLB',value:'DIFENHIDRAMINA HLB' },
  { text: 'BENADRYL',value:'BENADRYL' },
  { text: 'DIFENHIDRAMINA DENVER FA',value:'DIFENHIDRAMINA DENVER FA' },
  { text: 'BENADRYL DM COMPUESTO',value:'BENADRYL DM COMPUESTO' },
  { text: 'BENADRYL ANTITUSIVO',value:'BENADRYL ANTITUSIVO' },
  { text: 'LOTOQUIS 5',value:'LOTOQUIS 5' },
  { text: 'LOTOQUIS',value:'LOTOQUIS' },
  { text: 'LOTOQUIS SIMPLE',value:'LOTOQUIS SIMPLE' },
  { text: 'CARDIOGOXIN',value:'CARDIOGOXIN' },
  { text: 'LANOXIN (DIGOXINA)',value:'LANOXIN (DIGOXINA)' },
  { text: 'ATRIMON',value:'ATRIMON' },
  { text: 'HART',value:'HART' },
  { text: 'ACALIX',value:'ACALIX' },
  { text: 'INCORIL AP',value:'INCORIL AP' },
  { text: 'INCORIL',value:'INCORIL' },
  { text: 'ACALIX CRONOS',value:'ACALIX CRONOS' },
  { text: 'INCORIL MONODOSIS',value:'INCORIL MONODOSIS' },
  { text: 'ACALIX AP',value:'ACALIX AP' },
  { text: 'AGIRAX',value:'AGIRAX' },
  { text: 'DR. AMIN',value:'DR. AMIN' },
  { text: 'DRAMAMINE',value:'DRAMAMINE' },
  { text: 'NIKZON',value:'NIKZON' },
  { text: 'ATUREN',value:'ATUREN' },
  { text: 'MILCANOR 500',value:'MILCANOR 500' },
  { text: 'ALIVIAFLEB',value:'ALIVIAFLEB' },
  { text: 'VEDIPAL',value:'VEDIPAL' },
  { text: 'JATAMANSIN PLUS',value:'JATAMANSIN PLUS' },
  { text: 'VARINON',value:'VARINON' },
  { text: 'DIOSMIN',value:'DIOSMIN' },
  { text: 'DIPEMINA',value:'DIPEMINA' },
  { text: 'TERBENOL DUO',value:'TERBENOL DUO' },
  { text: 'TERBENOL DUO 1000',value:'TERBENOL DUO 1000' },
  { text: 'MILCANOR 1000',value:'MILCANOR 1000' },
  { text: 'DAFLON 1000',value:'DAFLON 1000' },
  { text: 'TERBENOL UD',value:'TERBENOL UD' },
  { text: 'DAFLON 500',value:'DAFLON 500' },
  { text: 'FLEVOMAX',value:'FLEVOMAX' },
  { text: 'FLEBOTROPIN 500',value:'FLEBOTROPIN 500' },
  { text: 'DIPIRONA HLB',value:'DIPIRONA HLB' },
  { text: 'NOVEMINA',value:'NOVEMINA' },
  { text: 'DIOXADOL',value:'DIOXADOL' },
  { text: 'NOVALGINA',value:'NOVALGINA' },
  { text: 'GASTRODOM',value:'GASTRODOM' },
  { text: 'DOMPERIX',value:'DOMPERIX' },
  { text: 'ESTOCALM',value:'ESTOCALM' },
  { text: 'MOPERIDONA',value:'MOPERIDONA' },
  { text: 'ECUAMON',value:'ECUAMON' },
  { text: 'BIGETRIC',value:'BIGETRIC' },
  { text: 'LUPRACIL',value:'LUPRACIL' },
  { text: 'CRIALIX',value:'CRIALIX' },
  { text: 'ONEFIN',value:'ONEFIN' },
  { text: 'DONENOVA',value:'DONENOVA' },
  { text: 'OLDINOT',value:'OLDINOT' },
  { text: 'VALPEX',value:'VALPEX' },
  { text: 'CRISTACLAR',value:'CRISTACLAR' },
  { text: 'DONEPES',value:'DONEPES' },
  { text: 'LIRPAN',value:'LIRPAN' },
  { text: 'CEBROCAL',value:'CEBROCAL' },
  { text: 'ENDOCLAR',value:'ENDOCLAR' },
  { text: 'AUROBRAL',value:'AUROBRAL' },
  { text: 'TRUSOPT',value:'TRUSOPT' },
  { text: 'DORLAMIDA',value:'DORLAMIDA' },
  { text: 'GLAUCOTENSIL TD LC',value:'GLAUCOTENSIL TD LC' },
  { text: 'DORZOLAMIDA T DORF',value:'DORZOLAMIDA T DORF' },
  { text: 'PRESS OUT T',value:'PRESS OUT T' },
  { text: 'DORZOFLAX',value:'DORZOFLAX' },
  { text: 'ZOPIROL DM',value:'ZOPIROL DM' },
  { text: 'ALIVIAPRES',value:'ALIVIAPRES' },
  { text: 'DORLAMIDA T',value:'DORLAMIDA T' },
  { text: 'TIMED D',value:'TIMED D' },
  { text: 'GLAUCOTENSIL TD',value:'GLAUCOTENSIL TD' },
  { text: 'COSOPT',value:'COSOPT' },
  { text: 'CARDURA',value:'CARDURA' },
  { text: 'DANOMICIN',value:'DANOMICIN' },
  { text: 'DOXICLINA',value:'DOXICLINA' },
  { text: 'ASOLMICINA.DOX',value:'ASOLMICINA.DOX' },
  { text: 'VERBORIL',value:'VERBORIL' },
  { text: 'DOXIBIOT',value:'DOXIBIOT' },
  { text: 'VIBRAMICINA',value:'VIBRAMICINA' },
  { text: 'ORACEA',value:'ORACEA' },
  { text: 'FUCSIA SIN ESTROGENOS',value:'FUCSIA SIN ESTROGENOS' },
  { text: 'KALI SIN ESTROGENOS',value:'KALI SIN ESTROGENOS' },
  { text: 'ISIS FREE SIN ESTROGENOS',value:'ISIS FREE SIN ESTROGENOS' },
  { text: 'SLINDA SIN ESTROGENOS',value:'SLINDA SIN ESTROGENOS' },
  { text: 'EOS',value:'EOS' },
  { text: 'GADOFEM',value:'GADOFEM' },
  { text: 'EQUIFEM',value:'EQUIFEM' },
  { text: 'ANGELIQ',value:'ANGELIQ' },
  { text: 'IFENIL',value:'IFENIL' },
  { text: 'KIRUMELLE',value:'KIRUMELLE' },
  { text: 'JADE MD',value:'JADE MD' },
  { text: 'JADE',value:'JADE' },
  { text: 'KALA MD 24',value:'KALA MD 24' },
  { text: 'KALA MD',value:'KALA MD' },
  { text: 'MAXIMA',value:'MAXIMA' },
  { text: 'KALA',value:'KALA' },
  { text: 'KIRUM',value:'KIRUM' },
  { text: 'ISIS',value:'ISIS' },
  { text: 'DAMSEL',value:'DAMSEL' },
  { text: 'DIVINA',value:'DIVINA' },
  { text: 'YASMIN',value:'YASMIN' },
  { text: 'IFENIL MD 24',value:'IFENIL MD 24' },
  { text: 'IFENIL MD',value:'IFENIL MD' },
  { text: 'DIVA TOTAL',value:'DIVA TOTAL' },
  { text: 'DIVA',value:'DIVA' },
  { text: 'YASMINELLE',value:'YASMINELLE' },
  { text: 'ISIS MINI 24',value:'ISIS MINI 24' },
  { text: 'ISIS MINI',value:'ISIS MINI' },
  { text: 'JADE MD 24',value:'JADE MD 24' },
  { text: 'KIR 28',value:'KIR 28' },
  { text: 'YAZ',value:'YAZ' },
  { text: 'MAXIMA MD 24',value:'MAXIMA MD 24' },
  { text: 'MAXIMA MD',value:'MAXIMA MD' },
  { text: 'DAMSELLA',value:'DAMSELLA' },
  { text: 'HEXAXIM',value:'HEXAXIM' },
  { text: 'IPINA',value:'IPINA' },
  { text: 'TENCAS',value:'TENCAS' },
  { text: 'ENATRAL 20 MG',value:'ENATRAL 20 MG' },
  { text: 'ENATRAL 5 MG',value:'ENATRAL 5 MG' },
  { text: 'ENATRAL 10 MG',value:'ENATRAL 10 MG' },
  { text: 'MAXEN',value:'MAXEN' },
  { text: 'ECAPRILAT',value:'ECAPRILAT' },
  { text: 'LOTRIAL',value:'LOTRIAL' },
  { text: 'GADOPRIL',value:'GADOPRIL' },
  { text: 'GLIOTEN',value:'GLIOTEN' },
  { text: 'VAPRESAN',value:'VAPRESAN' },
  { text: 'KINFIL',value:'KINFIL' },
  { text: 'RENITEC',value:'RENITEC' },
  { text: 'IPINA D',value:'IPINA D' },
  { text: 'MAXEN D',value:'MAXEN D' },
  { text: 'TENCAS D',value:'TENCAS D' },
  { text: 'GADOPRIL D',value:'GADOPRIL D' },
  { text: 'LOTRIAL D-20',value:'LOTRIAL D-20' },
  { text: 'GLIOTENZIDE',value:'GLIOTENZIDE' },
  { text: 'VAPRESAN DIUR',value:'VAPRESAN DIUR' },
  { text: 'KINFIL D',value:'KINFIL D' },
  { text: 'LOTRIAL D',value:'LOTRIAL D' },
  { text: 'CO-RENITEC',value:'CO-RENITEC' },
  { text: 'OMATEX',value:'OMATEX' },
  { text: 'DILUTOL',value:'DILUTOL' },
  { text: 'ENOXANORTH',value:'ENOXANORTH' },
  { text: 'CLEXANE',value:'CLEXANE' },
  { text: 'HEPARINOX',value:'HEPARINOX' },
  { text: 'COMTAN',value:'COMTAN' },
  { text: 'ERITROVIS',value:'ERITROVIS' },
  { text: 'OFTALMOLETS',value:'OFTALMOLETS' },
  { text: 'ERITROMED',value:'ERITROMED' },
  { text: 'ERISINE',value:'ERISINE' },
  { text: 'ERITROMICINA ELEA',value:'ERITROMICINA ELEA' },
  { text: 'ILOTICINA 4%',value:'ILOTICINA 4%' },
  { text: 'ERITROMICINA ATLAS',value:'ERITROMICINA ATLAS' },
  { text: 'ERI LOCION',value:'ERI LOCION' },
  { text: 'ERITROFARM',value:'ERITROFARM' },
  { text: 'KITACNE',value:'KITACNE' },
  { text: 'ERI ACNE',value:'ERI ACNE' },
  { text: 'PANTOMICINA',value:'PANTOMICINA' },
  { text: 'ERITRODERM',value:'ERITRODERM' },
  { text: 'ECNAGEL E',value:'ECNAGEL E' },
  { text: 'ERITROBRON FORTE',value:'ERITROBRON FORTE' },
  { text: 'ERITROBRON',value:'ERITROBRON' },
  { text: 'ELEVOPRAM',value:'ELEVOPRAM' },
  { text: 'ROSTALOPRAM',value:'ROSTALOPRAM' },
  { text: 'COVERFAX',value:'COVERFAX' },
  { text: 'OPTISER 10',value:'OPTISER 10' },
  { text: 'TALPRAM 10',value:'TALPRAM 10' },
  { text: 'ESCIPROX',value:'ESCIPROX' },
  { text: 'EX3',value:'EX3' },
  { text: 'MERIDIAN',value:'MERIDIAN' },
  { text: 'LEXTOR',value:'LEXTOR' },
  { text: 'NEXDIA',value:'NEXDIA' },
  { text: 'ESCITANOVA',value:'ESCITANOVA' },
  { text: 'LEXAPRO',value:'LEXAPRO' },
  { text: 'ESCITALOPRAM TEVA',value:'ESCITALOPRAM TEVA' },
  { text: 'REMPEC',value:'REMPEC' },
  { text: 'OPTISER 20',value:'OPTISER 20' },
  { text: 'AXIOMAT',value:'AXIOMAT' },
  { text: 'TALPRAM 20',value:'TALPRAM 20' },
  { text: 'BEAPLEN 20',value:'BEAPLEN 20' },
  { text: 'BEAPLEN 10',value:'BEAPLEN 10' },
  { text: 'ESCITEROKAM',value:'ESCITEROKAM' },
  { text: 'NOVO HUMORAP',value:'NOVO HUMORAP' },
  { text: 'ARAMIX',value:'ARAMIX' },
  { text: 'MERIDIAN 20',value:'MERIDIAN 20' },
  { text: 'ESOMEPRA 40 MG',value:'ESOMEPRA 40 MG' },
  { text: 'ULTREX 20',value:'ULTREX 20' },
  { text: 'ESOMAX',value:'ESOMAX' },
  { text: 'NEXIUM',value:'NEXIUM' },
  { text: 'ESOMEPRAZOL TEVA',value:'ESOMEPRAZOL TEVA' },
  { text: 'ESOGASTEC',value:'ESOGASTEC' },
  { text: 'SARMEC',value:'SARMEC' },
  { text: 'REFLUX',value:'REFLUX' },
  { text: 'SINULCUS',value:'SINULCUS' },
  { text: 'ADIKAN',value:'ADIKAN' },
  { text: 'ESOMEPRAZOL DENVER FAR',value:'ESOMEPRAZOL DENVER FAR' },
  { text: 'SOLUGASTRIL',value:'SOLUGASTRIL' },
  { text: 'ALZEPRAL',value:'ALZEPRAL' },
  { text: 'PRAZODEX',value:'PRAZODEX' },
  { text: 'ESOMEPRA 20 MG',value:'ESOMEPRA 20 MG' },
  { text: 'ESOGASTROSEDOL 40',value:'ESOGASTROSEDOL 40' },
  { text: 'ESOGASTROSEDOL',value:'ESOGASTROSEDOL' },
  { text: 'ULTREX 40',value:'ULTREX 40' },
  { text: 'ESOPRAZOL',value:'ESOPRAZOL' },
  { text: 'ROVAMYCINE',value:'ROVAMYCINE' },
  { text: 'REDIUN-E 100',value:'REDIUN-E 100' },
  { text: 'REDIUN-E 50',value:'REDIUN-E 50' },
  { text: 'REDIUN-E 25',value:'REDIUN-E 25' },
  { text: 'DRIMUX A',value:'DRIMUX A' },
  { text: 'ESPIRONOLACTONA DENVER',value:'ESPIRONOLACTONA DENVER' },
  { text: 'ALDACTONE A',value:'ALDACTONE A' },
  { text: 'LANX',value:'LANX' },
  { text: 'LASILACTON',value:'LASILACTON' },
  { text: 'ALDACTONE D 25/40',value:'ALDACTONE D 25/40' },
  { text: 'ALDACTONE D 25/20',value:'ALDACTONE D 25/20' },
  { text: 'ERROLON E',value:'ERROLON E' },
  { text: 'PROGYNOVA',value:'PROGYNOVA' },
  { text: 'RONFASE',value:'RONFASE' },
  { text: 'TRIAL GEL',value:'TRIAL GEL' },
  { text: 'RONTAGEL',value:'RONTAGEL' },
  { text: 'MESIGYNA SYR',value:'MESIGYNA SYR' },
  { text: 'MESIGYNA',value:'MESIGYNA' },
  { text: 'MENOCLIM CREMA',value:'MENOCLIM CREMA' },
  { text: 'MENOCLIM',value:'MENOCLIM' },
  { text: 'COLPOESTRIOL',value:'COLPOESTRIOL' },
  { text: 'HANEDA',value:'HANEDA' },
  { text: 'LIVIANNE 28',value:'LIVIANNE 28' },
  { text: 'VENISSE',value:'VENISSE' },
  { text: 'CUIDAFEM',value:'CUIDAFEM' },
  { text: 'ALELI',value:'ALELI' },
  { text: 'GINELEA MD 28',value:'GINELEA MD 28' },
  { text: 'SECRET 28',value:'SECRET 28' },
  { text: 'FEMIANE',value:'FEMIANE' },
  { text: 'GINELEA MD',value:'GINELEA MD' },
  { text: 'GINELEA',value:'GINELEA' },
  { text: 'ELLERING',value:'ELLERING' },
  { text: 'NUVARING',value:'NUVARING' },
  { text: 'ZARONTIN',value:'ZARONTIN' },
  { text: 'ESZOPIXEN',value:'ESZOPIXEN' },
  { text: 'NALECOL',value:'NALECOL' },
  { text: 'ALIPAS',value:'ALIPAS' },
  { text: 'ALIN',value:'ALIN' },
  { text: 'VADEL',value:'VADEL' },
  { text: 'CORACIL',value:'CORACIL' },
  { text: 'IXACOR',value:'IXACOR' },
  { text: 'EZETROL',value:'EZETROL' },
  { text: 'TRILIP',value:'TRILIP' },
  { text: 'ZETIA',value:'ZETIA' },
  { text: 'CRAVERIL DUO',value:'CRAVERIL DUO' },
  { text: 'MINUSLIP DUO',value:'MINUSLIP DUO' },
  { text: 'VASOTENAL EZ',value:'VASOTENAL EZ' },
  { text: 'ALIPAS DUO',value:'ALIPAS DUO' },
  { text: 'REDUSTEROL DUO',value:'REDUSTEROL DUO' },
  { text: 'VYTORIN',value:'VYTORIN' },
  { text: 'SENSU',value:'SENSU' },
  { text: 'TROPIOFTAL F',value:'TROPIOFTAL F' },
  { text: 'FOTORRETIN',value:'FOTORRETIN' },
  { text: 'APROCOM',value:'APROCOM' },
  { text: 'FENITOINA DENVER FARMA',value:'FENITOINA DENVER FARMA' },
  { text: 'EPAMIN',value:'EPAMIN' },
  { text: 'PRUDEMA',value:'PRUDEMA' },
  { text: 'FENROS',value:'FENROS' },
  { text: 'LUMINAL',value:'LUMINAL' },
  { text: 'ALEPSAL',value:'ALEPSAL' },
  { text: 'LUMINALETAS',value:'LUMINALETAS' },
  { text: 'PROCETOKEN',value:'PROCETOKEN' },
  { text: 'PROCETOKEN XR',value:'PROCETOKEN XR' },
  { text: 'LIPTUIN',value:'LIPTUIN' },
  { text: 'CONTROLIP',value:'CONTROLIP' },
  { text: 'SCLEROFIN U.D.',value:'SCLEROFIN U.D.' },
  { text: 'CRAVERIL',value:'CRAVERIL' },
  { text: 'SEGREN',value:'SEGREN' },
  { text: 'TEMPLARIS',value:'TEMPLARIS' },
  { text: 'MINUSLIP',value:'MINUSLIP' },
  { text: 'DAUNLIP',value:'DAUNLIP' },
  { text: 'MAGNOFEN TAB',value:'MAGNOFEN TAB' },
  { text: 'SERUBEL 135',value:'SERUBEL 135' },
  { text: 'SERUBEL 45',value:'SERUBEL 45' },
  { text: 'CRAVERIL XR',value:'CRAVERIL XR' },
  { text: 'MAGNOFEN',value:'MAGNOFEN' },
  { text: 'LIPOMAX',value:'LIPOMAX' },
  { text: 'GADOLIP',value:'GADOLIP' },
  { text: 'GRAMPENIL',value:'GRAMPENIL' },
  { text: 'PEN ORAL',value:'PEN ORAL' },
  { text: 'ALERFEDINE',value:'ALERFEDINE' },
  { text: 'ALERTIAL',value:'ALERTIAL' },
  { text: 'VAGRAN 180',value:'VAGRAN 180' },
  { text: 'VAGRAN 120',value:'VAGRAN 120' },
  { text: 'ALERCAS',value:'ALERCAS' },
  { text: 'ALERCAS CORT',value:'ALERCAS CORT' },
  { text: 'Q-PROST ALOPEX',value:'Q-PROST ALOPEX' },
  { text: 'UROTOTAL',value:'UROTOTAL' },
  { text: 'Q-PROST',value:'Q-PROST' },
  { text: 'RENACIDIN',value:'RENACIDIN' },
  { text: 'ANDROPEL',value:'ANDROPEL' },
  { text: 'SUTRICO',value:'SUTRICO' },
  { text: 'CAPILFOR',value:'CAPILFOR' },
  { text: 'FINASTERIN',value:'FINASTERIN' },
  { text: 'FINTERAC',value:'FINTERAC' },
  { text: 'PROPECIA',value:'PROPECIA' },
  { text: 'PROSTENE',value:'PROSTENE' },
  { text: 'PROSCAR',value:'PROSCAR' },
  { text: 'DIONDEL',value:'DIONDEL' },
  { text: 'FLENOMID XR',value:'FLENOMID XR' },
  { text: 'FARMICLOX',value:'FARMICLOX' },
  { text: 'FLUCONAL',value:'FLUCONAL' },
  { text: 'FUNGOCINA',value:'FUNGOCINA' },
  { text: 'FUNGOTOTAL',value:'FUNGOTOTAL' },
  { text: 'FLUPEC',value:'FLUPEC' },
  { text: 'MICORAL FLUCO',value:'MICORAL FLUCO' },
  { text: 'FLUCOGINKAN',value:'FLUCOGINKAN' },
  { text: 'ANTIMICON',value:'ANTIMICON' },
  { text: 'MICOLIS NOVO',value:'MICOLIS NOVO' },
  { text: 'PERIPLUM',value:'PERIPLUM' },
  { text: 'FLUZOL',value:'FLUZOL' },
  { text: 'HONGUIL PLUS',value:'HONGUIL PLUS' },
  { text: 'MUTUM',value:'MUTUM' },
  { text: 'ADOLCAS',value:'ADOLCAS' },
  { text: 'PRIDAMOS',value:'PRIDAMOS' },
  { text: 'FLUOXETINA TEVA',value:'FLUOXETINA TEVA' },
  { text: 'NERVOSAL',value:'NERVOSAL' },
  { text: 'FOXETIN 10',value:'FOXETIN 10' },
  { text: 'ANIMEX-ON',value:'ANIMEX-ON' },
  { text: 'EQUILIBRANE',value:'EQUILIBRANE' },
  { text: 'NEUPAX',value:'NEUPAX' },
  { text: 'FOXETIN',value:'FOXETIN' },
  { text: 'PROZAC',value:'PROZAC' },
  { text: 'DEXALERGIN CORT',value:'DEXALERGIN CORT' },
  { text: 'ALERNIX CORT',value:'ALERNIX CORT' },
  { text: 'BRONQUILAIR NASAL',value:'BRONQUILAIR NASAL' },
  { text: 'BALIVENT NASAL',value:'BALIVENT NASAL' },
  { text: 'INHALAN',value:'INHALAN' },
  { text: 'PROAIR NASAL',value:'PROAIR NASAL' },
  { text: 'LIDIL CORT',value:'LIDIL CORT' },
  { text: 'FLIXONASE ACUOSO NASAL',value:'FLIXONASE ACUOSO NASAL' },
  { text: 'FLUTICORT',value:'FLUTICORT' },
  { text: 'FLIXOTIDE',value:'FLIXOTIDE' },
  { text: 'ALENYS',value:'ALENYS' },
  { text: 'ASMABRON',value:'ASMABRON' },
  { text: 'FLUTIVENT HFA',value:'FLUTIVENT HFA' },
  { text: 'INHALAN BRONQUIAL 500/50 M',value:'INHALAN BRONQUIAL 500/50 M' },
  { text: 'INHALAN BRONQUIAL 250/50 M',value:'INHALAN BRONQUIAL 250/50 M' },
  { text: 'NEUMOTIDE POLVO 500/50',value:'NEUMOTIDE POLVO 500/50' },
  { text: 'NEUMOTIDE POLVO 250/50',value:'NEUMOTIDE POLVO 250/50' },
  { text: 'FLUTIVENT+AEROMED HFA',value:'FLUTIVENT+AEROMED HFA' },
  { text: 'PROAIR BRONQUIAL 500/50',value:'PROAIR BRONQUIAL 500/50' },
  { text: 'PROAIR BRONQUIAL 250/50',value:'PROAIR BRONQUIAL 250/50' },
  { text: 'PROAIR BRONQUIAL',value:'PROAIR BRONQUIAL' },
  { text: 'NEUMOTIDE AEROSOL CON A',value:'NEUMOTIDE AEROSOL CON A' },
  { text: 'NEUMOTIDE AEROSOL',value:'NEUMOTIDE AEROSOL' },
  { text: 'SERETIDE AEROSOL HFA',value:'SERETIDE AEROSOL HFA' },
  { text: 'SERETIDE DISKUS',value:'SERETIDE DISKUS' },
  { text: 'HLBFOLIC',value:'HLBFOLIC' },
  { text: 'ACIDO FOLICO RICHMOND',value:'ACIDO FOLICO RICHMOND' },
  { text: 'TANVIMIL FOLICO',value:'TANVIMIL FOLICO' },
  { text: 'BERNAFOLIC 5',value:'BERNAFOLIC 5' },
  { text: 'BERNAFOLIC 1',value:'BERNAFOLIC 1' },
  { text: 'NEXOVITAL FOLICO',value:'NEXOVITAL FOLICO' },
  { text: 'FOLINEMIC',value:'FOLINEMIC' },
  { text: 'ANFOLIC',value:'ANFOLIC' },
  { text: 'COFLIC',value:'COFLIC' },
  { text: 'SUPRAFOL',value:'SUPRAFOL' },
  { text: 'ACIFOL GOTAS',value:'ACIFOL GOTAS' },
  { text: 'EGESTAN FOLICO',value:'EGESTAN FOLICO' },
  { text: 'ACIFOL 10',value:'ACIFOL 10' },
  { text: 'ACIFOL 5',value:'ACIFOL 5' },
  { text: 'ACIFOL',value:'ACIFOL' },
  { text: 'FOLVITE',value:'FOLVITE' },
  { text: 'LIFECELL',value:'LIFECELL' },
  { text: 'MENOPUR',value:'MENOPUR' },
  { text: 'DAFUROSE',value:'DAFUROSE' },
  { text: 'FUROSEMIDA DENVER FARMA',value:'FUROSEMIDA DENVER FARMA' },
  { text: 'LASIX',value:'LASIX' },
  { text: 'FUROTRAL',value:'FUROTRAL' },
  { text: 'ERROLON',value:'ERROLON' },
  { text: 'ERROLON A',value:'ERROLON A' },
  { text: 'ACIFUSIN',value:'ACIFUSIN' },
  { text: 'ARZIMOL',value:'ARZIMOL' },
  { text: 'FUSITOP',value:'FUSITOP' },
  { text: 'GELBIOTIC',value:'GELBIOTIC' },
  { text: 'FUSITOP B',value:'FUSITOP B' },
  { text: 'ACIFUSIN B',value:'ACIFUSIN B' },
  { text: 'ARZIMOL B',value:'ARZIMOL B' },
  { text: 'GELBIOTIC PLUS',value:'GELBIOTIC PLUS' },
  { text: 'ARAPENTIN',value:'ARAPENTIN' },
  { text: 'ELIFER',value:'ELIFER' },
  { text: 'ULTRANEURAL',value:'ULTRANEURAL' },
  { text: 'AXILEP',value:'AXILEP' },
  { text: 'NEURONTIN',value:'NEURONTIN' },
  { text: 'LOGISTIC',value:'LOGISTIC' },
  { text: 'GAMMATET T',value:'GAMMATET T' },
  { text: 'TETABULIN S/D',value:'TETABULIN S/D' },
  { text: 'ORGALUTRAN',value:'ORGALUTRAN' },
  { text: 'LOPID UD',value:'LOPID UD' },
  { text: 'LOPID 600',value:'LOPID 600' },
  { text: 'GENTAREN',value:'GENTAREN' },
  { text: 'GLEVOMICINA',value:'GLEVOMICINA' },
  { text: 'PANCUTAN',value:'PANCUTAN' },
  { text: 'N14 GLIBE',value:'N14 GLIBE' },
  { text: 'DIABE PASS 5',value:'DIABE PASS 5' },
  { text: 'GLENTOR',value:'GLENTOR' },
  { text: 'GLIDANIL',value:'GLIDANIL' },
  { text: 'GARDOTON',value:'GARDOTON' },
  { text: 'DAONIL',value:'DAONIL' },
  { text: 'EUGLUCON',value:'EUGLUCON' },
  { text: 'ENDIAL MET 2',value:'ENDIAL MET 2' },
  { text: 'HIPOGLUT 4',value:'HIPOGLUT 4' },
  { text: 'HIPOGLUT 2',value:'HIPOGLUT 2' },
  { text: 'GLIMEPLIC',value:'GLIMEPLIC' },
  { text: 'DIABUTIL 2 MG',value:'DIABUTIL 2 MG' },
  { text: 'NEXT STEP 4',value:'NEXT STEP 4' },
  { text: 'NEXT STEP 2',value:'NEXT STEP 2' },
  { text: 'ADIUVAN',value:'ADIUVAN' },
  { text: 'GLEMAZ 2',value:'GLEMAZ 2' },
  { text: 'GLEMAZ',value:'GLEMAZ' },
  { text: 'ISLOPIR',value:'ISLOPIR' },
  { text: 'ENDIAL',value:'ENDIAL' },
  { text: 'AMARYL',value:'AMARYL' },
  { text: 'DIABUTIL 4 MG',value:'DIABUTIL 4 MG' },
  { text: 'GLEMAZ MET 4/1000',value:'GLEMAZ MET 4/1000' },
  { text: 'GLEMAZ MET 2/1000',value:'GLEMAZ MET 2/1000' },
  { text: 'ADIUVAN MET 4/1000',value:'ADIUVAN MET 4/1000' },
  { text: 'ADIUVAN MET 2/1000',value:'ADIUVAN MET 2/1000' },
  { text: 'HIPOGLUT MET',value:'HIPOGLUT MET' },
  { text: 'AMARYL M',value:'AMARYL M' },
  { text: 'ENDIAL MET 4',value:'ENDIAL MET 4' },
  { text: 'MINODIAB',value:'MINODIAB' },
  { text: 'BIFIDOSA',value:'BIFIDOSA' },
  { text: 'OVIDREL',value:'OVIDREL' },
  { text: 'DINARON',value:'DINARON' },
  { text: 'GONACOR 5000',value:'GONACOR 5000' },
  { text: 'HALOPERIDOL HLB',value:'HALOPERIDOL HLB' },
  { text: 'HALOPERIDOL MEDIPHARMA',value:'HALOPERIDOL MEDIPHARMA' },
  { text: 'ENABRAN',value:'ENABRAN' },
  { text: 'HALOPIDOL',value:'HALOPIDOL' },
  { text: 'HALOPERIDOL DENVER FARM',value:'HALOPERIDOL DENVER FARM' },
  { text: 'NEUPRAM',value:'NEUPRAM' },
  { text: 'HALOPIDOL DECANOATO',value:'HALOPIDOL DECANOATO' },
  { text: 'CYCLOPARIN',value:'CYCLOPARIN' },
  { text: 'HEPATRIET',value:'HEPATRIET' },
  { text: 'CERVEP',value:'CERVEP' },
  { text: 'HIDROCLOROTIAZIDA HLB',value:'HIDROCLOROTIAZIDA HLB' },
  { text: 'DIURAL',value:'DIURAL' },
  { text: 'DIUREX',value:'DIUREX' },
  { text: 'TANDIUR',value:'TANDIUR' },
  { text: 'DIUREX A',value:'DIUREX A' },
  { text: 'HIDRENOX A',value:'HIDRENOX A' },
  { text: 'DEMACORT',value:'DEMACORT' },
  { text: 'ALFACORT UNIDOSIS',value:'ALFACORT UNIDOSIS' },
  { text: 'ORALSONE',value:'ORALSONE' },
  { text: 'ANUSOL HC',value:'ANUSOL HC' },
  { text: 'MEDROCIL',value:'MEDROCIL' },
  { text: 'HIDROTISONA',value:'HIDROTISONA' },
  { text: 'MICROSONA',value:'MICROSONA' },
  { text: 'EVOQUIN',value:'EVOQUIN' },
  { text: 'NARBON',value:'NARBON' },
  { text: 'AXOKINE',value:'AXOKINE' },
  { text: 'PLAQUENIL',value:'PLAQUENIL' },
  { text: 'POLIRREUMIN',value:'POLIRREUMIN' },
  { text: 'PROLUTON DEPOT',value:'PROLUTON DEPOT' },
  { text: 'LAGRIMA DORF',value:'LAGRIMA DORF' },
  { text: 'LATLAS TEARS',value:'LATLAS TEARS' },
  { text: 'COOL TEARS',value:'COOL TEARS' },
  { text: 'ARTELAC',value:'ARTELAC' },
  { text: 'NATURA LAGRIMAS',value:'NATURA LAGRIMAS' },
  { text: 'HIDROXIUREA DELTA FARMA',value:'HIDROXIUREA DELTA FARMA' },
  { text: 'SIDERBLUT POLI',value:'SIDERBLUT POLI' },
  { text: 'SIDERBLUT GOTAS',value:'SIDERBLUT GOTAS' },
  { text: 'VITALIX',value:'VITALIX' },
  { text: 'SIDERBLUT IM',value:'SIDERBLUT IM' },
  { text: 'FERDROMACO PEDIATRICO',value:'FERDROMACO PEDIATRICO' },
  { text: 'TARDYFERON',value:'TARDYFERON' },
  { text: 'HEMOFER 200',value:'HEMOFER 200' },
  { text: 'HEMOFER',value:'HEMOFER' },
  { text: 'SIDERBLUT',value:'SIDERBLUT' },
  { text: 'FACTOFER GOTAS',value:'FACTOFER GOTAS' },
  { text: 'FER IN SOL',value:'FER IN SOL' },
  { text: 'IBEROL',value:'IBEROL' },
  { text: 'FERRO FOLIC',value:'FERRO FOLIC' },
  { text: 'FACTOFER B12',value:'FACTOFER B12' },
  { text: 'YECTAFER TABS',value:'YECTAFER TABS' },
  { text: 'SIDERBLUT FOLIC',value:'SIDERBLUT FOLIC' },
  { text: 'HIERROQUICK 80',value:'HIERROQUICK 80' },
  { text: 'HIERROQUICK 40',value:'HIERROQUICK 40' },
  { text: 'VITALIX COMPLEX',value:'VITALIX COMPLEX' },
  { text: 'ACIFOL FE',value:'ACIFOL FE' },
  { text: 'HEMOVIT',value:'HEMOVIT' },
  { text: 'REXFOL',value:'REXFOL' },
  { text: 'TENVIC',value:'TENVIC' },
  { text: 'SIDERBLUT COMPLEX',value:'SIDERBLUT COMPLEX' },
  { text: 'ANEMIDOX ULTRA',value:'ANEMIDOX ULTRA' },
  { text: 'NEXOVITAL COMPLEX',value:'NEXOVITAL COMPLEX' },
  { text: 'ANEMIDOX FERRUM',value:'ANEMIDOX FERRUM' },
  { text: 'YECTAFER COMPLEX',value:'YECTAFER COMPLEX' },
  { text: 'RUBIRON',value:'RUBIRON' },
  { text: 'HOMATROPINA LAFEDAR',value:'HOMATROPINA LAFEDAR' },
  { text: 'FACTOR AG ANTIESPASMODIC',value:'FACTOR AG ANTIESPASMODIC' },
  { text: 'SILIDRAL UNO',value:'SILIDRAL UNO' },
  { text: 'DELTROX',value:'DELTROX' },
  { text: 'MODIFICAL',value:'MODIFICAL' },
  { text: 'BONVIVA',value:'BONVIVA' },
  { text: 'ADROMUX',value:'ADROMUX' },
  { text: 'DISDUAL',value:'DISDUAL' },
  { text: 'TABTIL',value:'TABTIL' },
  { text: 'BREXELL PLUS',value:'BREXELL PLUS' },
  { text: 'BANTUC',value:'BANTUC' },
  { text: 'MESEL',value:'MESEL' },
  { text: 'FEMOREL',value:'FEMOREL' },
  { text: 'IDENA',value:'IDENA' },
  { text: 'IBANLEG',value:'IBANLEG' },
  { text: 'SIEND',value:'SIEND' },
  { text: 'IBUMULTIN',value:'IBUMULTIN' },
  { text: 'IBUPROFENO TEVA',value:'IBUPROFENO TEVA' },
  { text: 'ACTRON PEDIATRICO 4%',value:'ACTRON PEDIATRICO 4%' },
  { text: 'IBUPIRAC 600 CAPSULA BLAN',value:'IBUPIRAC 600 CAPSULA BLAN' },
  { text: 'IBUPIRAC SUSPENSION 4%',value:'IBUPIRAC SUSPENSION 4%' },
  { text: 'IBUPIRAC 800 MG',value:'IBUPIRAC 800 MG' },
  { text: 'IBUMEJORAL 600 RAPIDA ACC',value:'IBUMEJORAL 600 RAPIDA ACC' },
  { text: 'IBUMEJORAL 600',value:'IBUMEJORAL 600' },
  { text: 'IBUSOL',value:'IBUSOL' },
  { text: 'ACTRON 600 RAPIDA ACCION',value:'ACTRON 600 RAPIDA ACCION' },
  { text: 'FEBRATIC 4%',value:'FEBRATIC 4%' },
  { text: 'IBUPIRETAS JR.',value:'IBUPIRETAS JR.' },
  { text: 'IBUPIRAC GOTAS',value:'IBUPIRAC GOTAS' },
  { text: 'VEFREN 600',value:'VEFREN 600' },
  { text: 'VEFREN 400',value:'VEFREN 400' },
  { text: 'AFEBRIL FORTE',value:'AFEBRIL FORTE' },
  { text: 'FEBRATIC',value:'FEBRATIC' },
  { text: 'IBUPIRAC 600 MG',value:'IBUPIRAC 600 MG' },
  { text: 'ACTRON FLEX',value:'ACTRON FLEX' },
  { text: 'IBUPIRAC FLEX CAPSULAS BL',value:'IBUPIRAC FLEX CAPSULAS BL' },
  { text: 'IBUMEJORAL FLEX 600',value:'IBUMEJORAL FLEX 600' },
  { text: 'IBUMEJORAL FLEX',value:'IBUMEJORAL FLEX' },
  { text: 'IBUPIRAC FLEX 600',value:'IBUPIRAC FLEX 600' },
  { text: 'FLEXINA 600',value:'FLEXINA 600' },
  { text: 'IBUPIRAC FLEX',value:'IBUPIRAC FLEX' },
  { text: 'IMIQUIMOD HLB',value:'IMIQUIMOD HLB' },
  { text: 'IMIQA',value:'IMIQA' },
  { text: 'MIQUIMOD',value:'MIQUIMOD' },
  { text: 'VIROSUPRIL 3.75',value:'VIROSUPRIL 3.75' },
  { text: 'VIROSUPRIL',value:'VIROSUPRIL' },
  { text: 'ONBRIZE BREEZHALER',value:'ONBRIZE BREEZHALER' },
  { text: 'NORANAT SR',value:'NORANAT SR' },
  { text: 'NATRILIX SR',value:'NATRILIX SR' },
  { text: 'NORANAT',value:'NORANAT' },
  { text: 'IM 75 MONTPELLIER',value:'IM 75 MONTPELLIER' },
  { text: 'INDOTEX',value:'INDOTEX' },
  { text: 'AEROTROP',value:'AEROTROP' },
  { text: 'ATROVENT HFA',value:'ATROVENT HFA' },
  { text: 'ATROVENT',value:'ATROVENT' },
  { text: 'MEDOCOR SUBLINGUAL',value:'MEDOCOR SUBLINGUAL' },
  { text: 'MEDOCOR',value:'MEDOCOR' },
  { text: 'MEDOCOR AP',value:'MEDOCOR AP' },
  { text: 'ATLACNE',value:'ATLACNE' },
  { text: 'ISOTAN',value:'ISOTAN' },
  { text: 'FLEXRESAN',value:'FLEXRESAN' },
  { text: 'ROACCUTAN',value:'ROACCUTAN' },
  { text: 'CITINEXIN',value:'CITINEXIN' },
  { text: 'DUVADILAN',value:'DUVADILAN' },
  { text: 'ITRAISDIN',value:'ITRAISDIN' },
  { text: 'SALIMIDIN 200',value:'SALIMIDIN 200' },
  { text: 'NITRIDAZOL',value:'NITRIDAZOL' },
  { text: 'SALIMIDIN 100',value:'SALIMIDIN 100' },
  { text: 'SPORANOX PULSO',value:'SPORANOX PULSO' },
  { text: 'ROSATINA',value:'ROSATINA' },
  { text: 'NOPUCID IVER',value:'NOPUCID IVER' },
  { text: 'LICEND',value:'LICEND' },
  { text: 'IVER P',value:'IVER P' },
  { text: 'SECURO',value:'SECURO' },
  { text: 'QUADION',value:'QUADION' },
  { text: 'KETONAZOL LAFEDAR',value:'KETONAZOL LAFEDAR' },
  { text: 'FANGAN',value:'FANGAN' },
  { text: 'KEDUO',value:'KEDUO' },
  { text: 'MICORAL',value:'MICORAL' },
  { text: 'FITONAL',value:'FITONAL' },
  { text: 'ORIFUNGAL',value:'ORIFUNGAL' },
  { text: 'FANGAN DUO',value:'FANGAN DUO' },
  { text: 'KPAN',value:'KPAN' },
  { text: 'ELGYDOL',value:'ELGYDOL' },
  { text: 'DUPRAC',value:'DUPRAC' },
  { text: 'DUPRAC SL',value:'DUPRAC SL' },
  { text: 'KERAMIX RAPID',value:'KERAMIX RAPID' },
  { text: 'KERAMIX',value:'KERAMIX' },
  { text: 'DORIXINA FORTE NF',value:'DORIXINA FORTE NF' },
  { text: 'TELEDOL',value:'TELEDOL' },
  { text: 'TELEDOL SL',value:'TELEDOL SL' },
  { text: 'ACULAR LS',value:'ACULAR LS' },
  { text: 'UNICALM',value:'UNICALM' },
  { text: 'SINALGICO SL',value:'SINALGICO SL' },
  { text: 'DOLTEN SL',value:'DOLTEN SL' },
  { text: 'SINALGICO',value:'SINALGICO' },
  { text: 'ACULAR',value:'ACULAR' },
  { text: 'POENKERAT',value:'POENKERAT' },
  { text: 'DOLTEN',value:'DOLTEN' },
  { text: 'KETIAL RAPID',value:'KETIAL RAPID' },
  { text: 'KETIAL',value:'KETIAL' },
  { text: 'CALCIO BASE EFERVESCENTE',value:'CALCIO BASE EFERVESCENTE' },
  { text: 'LAMIRAX',value:'LAMIRAX' },
  { text: 'LAMOCAS',value:'LAMOCAS' },
  { text: 'LATRIGIN 25',value:'LATRIGIN 25' },
  { text: 'EPILEPAX',value:'EPILEPAX' },
  { text: 'LAGOTRAN',value:'LAGOTRAN' },
  { text: 'LAMICTAL DISPERSABLE',value:'LAMICTAL DISPERSABLE' },
  { text: 'LAMOCAS XR',value:'LAMOCAS XR' },
  { text: 'LATRIGIN 200',value:'LATRIGIN 200' },
  { text: 'LATRIGIN 100',value:'LATRIGIN 100' },
  { text: 'LATRIGIN 50',value:'LATRIGIN 50' },
  { text: 'XOMEPRASEC',value:'XOMEPRASEC' },
  { text: 'ACIMED L',value:'ACIMED L' },
  { text: 'LANSOPRAZOL TEVA',value:'LANSOPRAZOL TEVA' },
  { text: 'LANZOPRAL MD',value:'LANZOPRAL MD' },
  { text: 'LANZOPRAL',value:'LANZOPRAL' },
  { text: 'LOUTEN',value:'LOUTEN' },
  { text: 'OFTALPRES',value:'OFTALPRES' },
  { text: 'GLAUCOGESIC',value:'GLAUCOGESIC' },
  { text: 'LATANOPROST DORF',value:'LATANOPROST DORF' },
  { text: 'GLAUCOSTAT',value:'GLAUCOSTAT' },
  { text: 'OCUPROST',value:'OCUPROST' },
  { text: 'XALATAN',value:'XALATAN' },
  { text: 'LATANOFLAX',value:'LATANOFLAX' },
  { text: 'LATANOFLAX T',value:'LATANOFLAX T' },
  { text: 'GLAUCOGESIC T',value:'GLAUCOGESIC T' },
  { text: 'GLAUCOSTAT T',value:'GLAUCOSTAT T' },
  { text: 'LATIMODORF',value:'LATIMODORF' },
  { text: 'XALACOM',value:'XALACOM' },
  { text: 'LOUTEN T',value:'LOUTEN T' },
  { text: 'FLUDART',value:'FLUDART' },
  { text: 'LEFLULEP',value:'LEFLULEP' },
  { text: 'FLUXAP',value:'FLUXAP' },
  { text: 'LEFLUNOMIDA SC',value:'LEFLUNOMIDA SC' },
  { text: 'LEFLUAR',value:'LEFLUAR' },
  { text: 'AFIANCEN',value:'AFIANCEN' },
  { text: 'FILARTROS',value:'FILARTROS' },
  { text: 'INMUNOARTRO',value:'INMUNOARTRO' },
  { text: 'ARAVA',value:'ARAVA' },
  { text: 'ETABYX',value:'ETABYX' },
  { text: 'LEVRON',value:'LEVRON' },
  { text: 'MOLIVAL',value:'MOLIVAL' },
  { text: 'CALLEXE',value:'CALLEXE' },
  { text: 'KEPPRA',value:'KEPPRA' },
  { text: 'EQUILEA',value:'EQUILEA' },
  { text: 'LEPTAM',value:'LEPTAM' },
  { text: 'LAFONTEN',value:'LAFONTEN' },
  { text: 'RACETAM',value:'RACETAM' },
  { text: 'LEVENOVA',value:'LEVENOVA' },
  { text: 'LEVECOM SOLUCIÓN',value:'LEVECOM SOLUCIÓN' },
  { text: 'LEVECOM 1000',value:'LEVECOM 1000' },
  { text: 'LEVECOM 500',value:'LEVECOM 500' },
  { text: 'LEVITAL',value:'LEVITAL' },
  { text: 'LEVECOM XR 750',value:'LEVECOM XR 750' },
  { text: 'LEVECOM XR 500',value:'LEVECOM XR 500' },
  { text: 'LEVAXON',value:'LEVAXON' },
  { text: 'CALLEXE XR',value:'CALLEXE XR' },
  { text: 'KEPPRA IV',value:'KEPPRA IV' },
  { text: 'VECETAM 1000',value:'VECETAM 1000' },
  { text: 'VECETAM 500',value:'VECETAM 500' },
  { text: 'MOLIVAL 1000',value:'MOLIVAL 1000' },
  { text: 'MOLIVAL 500',value:'MOLIVAL 500' },
  { text: 'MADOPAR',value:'MADOPAR' },
  { text: 'MADOPAR HBS',value:'MADOPAR HBS' },
  { text: 'MADOPAR DISPERSABLE',value:'MADOPAR DISPERSABLE' },
  { text: 'PARKINEL',value:'PARKINEL' },
  { text: 'LEBOCAR',value:'LEBOCAR' },
  
          
        ];
        const modal = ref();
        const selectedMedicamentoText = ref('0 Items');
        const selectedmedicamentos = ref([]);
  
        const formatData = (data: string[]) => {
          if (data.length === 1) {
            const medicamento = medicamentos.find((medicamento) => medicamento.value === data[0]);
            return medicamento.text;
          }
  
          return `${data.length} items`;
        };
  
        const medicamentoselectionChanged = (medicamentos: string[]) => {
          selectedmedicamentos.value = medicamentos;
          selectedMedicamentoText.value = formatData(selectedmedicamentos.value);
          modal.value.$el.dismiss();
        };
        
        
        return { modal, medicamentos, selectedMedicamentoText, selectedmedicamentos, medicamentoselectionChanged };
      },
    });
  </script>