import { createStore } from 'vuex';

const store = createStore({
  state() {
    return {
		user: null,
		token: null,
		user_id: null,
		assurance_id: null,
		role_id: null,
		surname: null,
		dni: null,
		borndate: null,
		name: null,
		mail: null,
		cellphone: null,
		user: null,
		password: null,
		password_date: null,
		login_date: null,
		rol: null,
		posologies_id: null,
		id_medication_type: null,
		posologies_name: null,
		instructions: null,
		medical_order_date: null,
		frequency: null,
		quantity_day: null,
		type: null,
		plan: null,
		assurance_number: null,
		diagnostic_id: null,
		posologie_id: null,
		treatment_date: null,
		treatment_hour: null,
		diagnostic: null,
		MEDICATION_TYPES_id: null,
		pharmeceutical_name: null,
		instructions: null,
		unit: null,
		drug_quantity: null,
		expiration_date: null,
		laboratory: null,
		RELATIONS_USERS_id: null,
		id_user_1: null,
		id_user_2: null,
		id_alarm: null,
		ALARMS_id: null,
		alarm_type: null,
		date: null,
		name: null,
		alarm_hour: null,
		alarm_start: null
    };
  },
  mutations: {
setUser(state, user) {state.user = user; },
setToken(state, token) {state.token = token;},
setUserId(state, user_id) {state.user_id = user_id;},
setAssurance_id(state,assurance_id){state.assurance_id=assurance_id;},
setRole_id(state,role_id){state.role_id=role_id;},
setSurname(state,surname){state.surname=surname;},
setDni(state,dni){state.dni=dni;},
setBorndate(state,borndate){state.borndate=borndate;},
setName(state,name){state.name=name;},
setMail(state,mail){state.mail=mail;},
setCellphone(state,cellphone){state.cellphone=cellphone;},
setPassword(state,password){state.password=password;},
setPassword_date(state,password_date){state.password_date=password_date;},
setLogin_date(state,login_date){state.login_date=login_date;},
setRol(state,rol){state.rol=rol;},
setPosologies_id(state,posologies_id){state.posologies_id=posologies_id;},
setId_medication_type(state,id_medication_type){state.id_medication_type=id_medication_type;},
setPosologies_name(state,posologies_name){state.posologies_name=posologies_name;},
setInstructions(state,instructions){state.instructions=instructions;},
setMedical_order_date(state,medical_order_date){state.medical_order_date=medical_order_date;},
setFrequency(state,frequency){state.frequency=frequency;},
setQuantity_day(state,quantity_day){state.quantity_day=quantity_day;},
setType(state,type){state.type=type;},
setPlan(state,plan){state.plan=plan;},
setAssurance_number(state,assurance_number){state.assurance_number=assurance_number;},
setDiagnostic_id(state,diagnostic_id){state.diagnostic_id=diagnostic_id;},
setPosologie_id(state,posologie_id){state.posologie_id=posologie_id;},
setTreatment_date(state,treatment_date){state.treatment_date=treatment_date;},
setTreatment_hour(state,treatment_hour){state.treatment_hour=treatment_hour;},
setDiagnostic(state,diagnostic){state.diagnostic=diagnostic;},
setMEDICATION_TYPES_id(state,MEDICATION_TYPES_id){state.MEDICATION_TYPES_id=MEDICATION_TYPES_id;},
setPharmeceutical_name(state,pharmeceutical_name){state.pharmeceutical_name=pharmeceutical_name;},
setInstructions(state,instructions){state.instructions=instructions;},
setUnit(state,unit){state.unit=unit;},
setDrug_quantity(state,drug_quantity){state.drug_quantity=drug_quantity;},
setExpiration_date(state,expiration_date){state.expiration_date=expiration_date;},
setLaboratory(state,laboratory){state.laboratory=laboratory;},
setRELATIONS_USERS_id(state,RELATIONS_USERS_id){state.RELATIONS_USERS_id=RELATIONS_USERS_id;},
setId_user_1(state,id_user_1){state.id_user_1=id_user_1;},
setId_user_2(state,id_user_2){state.id_user_2=id_user_2;},
setId_alarm(state,id_alarm){state.id_alarm=id_alarm;},
setALARMS_id(state,ALARMS_id){state.ALARMS_id=ALARMS_id;},
setAlarm_type(state,alarm_type){state.alarm_type=alarm_type;},
setDate(state,date){state.date=date;},
setName(state,name){state.name=name;},
setAlarm_hour(state,alarm_hour){state.alarm_hour=alarm_hour;},
setAlarm_start(state,alarm_start){state.alarm_start=alarm_start;},
	
  },
});

export default store;